Repository Agenta-AI/agenta, pull requests merged in 2023-08, with the labels that each got.

#201 rename: rename dataset to testset
  README.md
  agenta-backend/agenta_backend/main.py
  agenta-backend/agenta_backend/models/api/app_evaluation_model.py
  agenta-backend/agenta_backend/models/api/testset_model.py
  agenta-backend/agenta_backend/routers/app_evaluation_router.py
  agenta-backend/agenta_backend/routers/dataset_router.py
  agenta-backend/agenta_backend/routers/testset_router.py
  agenta-backend/agenta_backend/services/app_manager.py
  agenta-backend/agenta_backend/services/db_mongo.py
  agenta-backend/db/migration/mongodb/001_dataset_to_testset.py
  agenta-web/src/code_snippets/testsets/create_with_json/curl.ts
  agenta-web/src/code_snippets/testsets/create_with_json/python.ts
  agenta-web/src/code_snippets/testsets/create_with_json/typescript.ts
  agenta-web/src/code_snippets/testsets/create_with_upload/curl.ts
  agenta-web/src/code_snippets/testsets/create_with_upload/python.ts
  agenta-web/src/code_snippets/testsets/create_with_upload/typescript.ts
  agenta-web/src/components/EvaluationTable/EvaluationTable.tsx
  agenta-web/src/components/EvaluationTable/ExactMatchEvaluationTable.tsx
  agenta-web/src/components/EvaluationTable/SimilarityMatchEvaluationTable.tsx
  agenta-web/src/components/Evaluations/Evaluations.tsx
  agenta-web/src/components/Evaluations/EvaluationsList.tsx
  agenta-web/src/components/Playground/LoadTestsModal.tsx
  agenta-web/src/components/TestSetTable/InsertTestsetNameModal.tsx
  agenta-web/src/components/TestSetTable/TestsetTable.tsx
  agenta-web/src/lib/Types.ts
  agenta-web/src/lib/services/api.ts
  agenta-web/src/lib/transformers.ts
  agenta-web/src/pages/apps/[app_name]/testsets/[testset_id]/index.tsx
  agenta-web/src/pages/apps/[app_name]/testsets/index.tsx
  agenta-web/src/pages/apps/[app_name]/testsets/new/api/index.tsx
  agenta-web/src/pages/apps/[app_name]/testsets/new/manual/index.tsx
  agenta-web/src/pages/apps/[app_name]/testsets/new/upload/index.tsx
  docs/migration/migration.mdx
  docs/mint.json
Labels: refactoring

#252 Added FloatParam Min and Max optional parameters
  agenta-cli/agenta/__init__.py
  agenta-cli/agenta/sdk/__init__.py
  agenta-cli/agenta/sdk/agenta.py
  agenta-cli/agenta/sdk/types.py
  agenta-web/src/components/Playground/Views/ParametersView.tsx
  agenta-web/src/lib/Types.ts
  agenta-web/src/lib/helpers/openapi_parser.ts
  docs/mint.json.old
  docs/tutorials/your-first-llm-app.mdx
  examples/sales_transcript_summarizer/app.py
Labels: SDK

#269 updates package.json and version for lock file
  agenta-web/package-lock.json
  agenta-web/package.json
Labels: bug, dependencies

#266 refactor: change app_evaluation filename to evaluation
  .flake8
  agenta-backend/agenta_backend/main.py
  agenta-backend/agenta_backend/models/api/evaluation_model.py
  agenta-backend/agenta_backend/routers/evaluation_router.py
  agenta-backend/agenta_backend/services/db_mongo.py
  agenta-web/src/components/Evaluations/Evaluations.tsx
  agenta-web/src/components/Results/Results.tsx
  agenta-web/src/lib/services/api.ts
Labels: refactoring

#243 Feat- improve org of variants in code and playground & cli progress updates
  agenta-backend/agenta_backend/routers/app_variant.py
  agenta-cli/agenta/cli/variant_commands.py
  agenta-web/src/components/Playground/NewVariantModal.tsx
  agenta-web/src/components/Playground/VersionTabs.tsx
  docs/getting-started.mdx
  docs/howto/creating-multiple-app-variants.mdx
  docs/reference/agenta-cli.mdx
  docs/tutorials/your-first-llm-app.mdx
Labels: enhancement, CLI

#263 Feat: sdk v2 add new intparam
  agenta-cli/agenta/__init__.py
  agenta-cli/agenta/sdk/__init__.py
  agenta-cli/agenta/sdk/agenta.py
  agenta-cli/agenta/sdk/types.py
  agenta-web/src/components/Playground/Views/ParametersView.tsx
  agenta-web/src/lib/helpers/openapi_parser.ts
  examples/sales_transcript_summarizer/app.py
Labels: enhancement, SDK

#479 created new feature flag and disabled api view at demo version
  agenta-web/src/pages/apps/[app_name]/testsets/index.tsx
  docker-compose.prod.yml
  docker-compose.yml
Labels: Frontend

#493 hotfix
  agenta-backend/agenta_backend/services/app_manager.py
Labels: bug
