Repository Agenta-AI/agenta, pull requests merged in 2023-07, with the labels that each got.

#75 Cli deploy to prod
  agenta-backend/agenta_backend/config.py
  agenta-backend/agenta_backend/routers/container_manager.py
  agenta-backend/agenta_backend/services/docker_utils.py
  agenta-cli/agenta/cli/helper.py
  agenta-cli/agenta/cli/main.py
  agenta-cli/agenta/cli/variant_commands.py
  agenta-cli/agenta/client/client.py
  agenta-cli/agenta/config.py
  agenta-cli/agenta/config.toml
  agenta-cli/agenta/docker/docker_utils.py
  agenta-cli/pyproject.toml
  docker-compose.prod.yml
  docker-compose.yml
  docs/conceptual/concepts.mdx
  docs/reference/agenta-cli.mdx
Labels: bug, documentation, enhancement

#78 removed tooltip will be implemented soon
  agenta-web/src/components/AppSelector/AppCard.tsx
Labels: bug

#77 Improved error messaging in UI
  agenta-cli/agenta/sdk/agenta.py
  agenta-cli/pyproject.toml
Labels: bug, enhancement

#82 Edit dataset
  agenta-backend/agenta_backend/routers/dataset_router.py
  agenta-web/src/components/TestSetTable/TestSetTable.tsx
  agenta-web/src/lib/services/api.ts
  agenta-web/src/pages/apps/[app_name]/testsets/[testset_id]/index.tsx
  agenta-web/src/pages/apps/[app_name]/testsets/index.tsx
  agenta-web/src/pages/apps/[app_name]/testsets/new/manual/index.tsx
  agenta-web/src/pages/apps/[app_name]/testsets/new/upload/index.tsx
Labels: enhancement

#87 Upload via api
  agenta-web/src/code_snippets/testsets/create_with_json/curl.ts
  agenta-web/src/code_snippets/testsets/create_with_json/python.ts
  agenta-web/src/code_snippets/testsets/create_with_json/typescript.ts
  agenta-web/src/code_snippets/testsets/create_with_upload/curl.ts
  agenta-web/src/code_snippets/testsets/create_with_upload/python.ts
  agenta-web/src/code_snippets/testsets/create_with_upload/typescript.ts
  agenta-web/src/components/DynamicCodeBlock/DynamicCodeBlock.tsx
  agenta-web/src/pages/apps/[app_name]/endpoints/[variant_id]/index.tsx
  agenta-web/src/pages/apps/[app_name]/testsets/index.tsx
  agenta-web/src/pages/apps/[app_name]/testsets/new/api/index.tsx
Labels: enhancement

#92 removed soon elements
  agenta-web/src/components/Sidebar/Sidebar.tsx
Labels: enhancement

#119 Make the test cases work with the same values on all variants
  agenta-web/src/components/Playground/TestContextProvider.tsx
  agenta-web/src/components/Playground/VersionTabs.tsx
  agenta-web/src/components/Playground/Views/TestView.tsx
Labels: enhancement, Frontend

#163 Partial solution from #160
  agenta-web/src/components/AppSelector/AppCard.tsx
  agenta-web/src/components/DynamicCodeBlock/DynamicCodeBlock.tsx
  agenta-web/src/components/Evaluations/Evaluations.tsx
  agenta-web/src/components/Playground/VersionTabs.tsx
  agenta-web/src/lib/Types.ts
Labels: Frontend
