Repository Agenta-AI/agenta, pull requests merged in 2024-01, with the labels that each got.

#1144 Refactor variable renaming in utils.ts
  agenta-web/src/lib/helpers/utils.ts
Labels: Frontend

#1145 Add Tooltip for adding all conversation turns in AddToTestSetDrawer
  agenta-web/src/components/Playground/AddToTestSetDrawer/AddToTestSetDrawer.tsx
Labels: Frontend

#1149 Feat: Migrate Agenta to use Beanie ODM
  agenta-backend/agenta_backend/main.py
  agenta-backend/agenta_backend/models/api/evaluation_model.py
  agenta-backend/agenta_backend/models/db_engine.py
  agenta-backend/agenta_backend/models/db_models.py
  agenta-backend/agenta_backend/resources/evaluators/evaluators.json
  agenta-backend/agenta_backend/routers/app_router.py
  agenta-backend/agenta_backend/routers/container_router.py
  agenta-backend/agenta_backend/routers/evaluators_router.py
  agenta-backend/agenta_backend/routers/human_evaluation_router.py
  agenta-backend/agenta_backend/routers/testset_router.py
  agenta-backend/agenta_backend/routers/variants_router.py
  agenta-backend/agenta_backend/services/db_manager.py
  agenta-backend/agenta_backend/services/evaluation_service.py
  agenta-backend/agenta_backend/services/evaluators_service.py
  agenta-backend/agenta_backend/services/event_db_manager.py
  agenta-backend/agenta_backend/services/results_service.py
  agenta-backend/agenta_backend/services/selectors.py
  agenta-backend/agenta_backend/tasks/evaluations.py
  agenta-backend/agenta_backend/tests/conftest.py
  agenta-backend/agenta_backend/tests/observability_router/conftest.py
  agenta-backend/agenta_backend/tests/variants_evaluators_router/conftest.py
  agenta-backend/agenta_backend/tests/variants_main_router/conftest.py
  agenta-backend/agenta_backend/tests/variants_main_router/test_app_variant_router.py
  agenta-backend/agenta_backend/tests/variants_main_router/test_observability_router.py
  agenta-backend/agenta_backend/tests/variants_main_router/test_variant_evaluators_router.py
  agenta-backend/agenta_backend/tests/variants_main_router/test_variant_testset_router.py
  agenta-backend/agenta_backend/tests/variants_organization_router/test_organization_router.py
  agenta-backend/agenta_backend/tests/variants_router/conftest.py
  agenta-backend/agenta_backend/tests/variants_user_profile_router/test_user_profile.py
  agenta-backend/agenta_backend/utils/common.py
  agenta-backend/poetry.lock
  agenta-backend/pyproject.toml
  agenta-cli/poetry.lock
  agenta-web/src/components/Evaluations/AutomaticEvaluationResult.tsx
  agenta-web/src/components/pages/evaluations/evaluators/NewEvaluatorModal.tsx
Labels: enhancement, Backend

#1169 Fix register_default overwrite behavior
  agenta-backend/agenta_backend/routers/configs_router.py
  agenta-backend/agenta_backend/services/app_manager.py
  agenta-cli/agenta/sdk/agenta_init.py
Labels: bug
