Repository Agenta-AI/agenta, pull requests merged in 2024-10, with the labels that each got.

#2094 Fix Bugs for v0.25.0 Release
  agenta-backend/agenta_backend/models/converters.py
  agenta-backend/agenta_backend/resources/evaluators/evaluators.py
Labels: bug, Backend, size:S, lgtm

#2097 fix (bug): resolve error when starting application variant container
  agenta-backend/agenta_backend/services/app_manager.py
Labels: bug, Backend, size:XS, lgtm

#2095 Update README.md
  README.md
Labels: documentation, size:S, lgtm

#2099 Update README.md
  README.md
Labels: documentation, size:XS, lgtm

#2100 fix(frontend): Wrong endpoint in deployment fetch prompt
  agenta-web/src/code_snippets/endpoints/fetch_config/curl.ts
  agenta-web/src/code_snippets/endpoints/fetch_config/python.ts
  agenta-web/src/code_snippets/endpoints/fetch_config/typescript.ts
  agenta-web/src/pages/apps/[app_id]/testsets/index.tsx
Labels: bug, Frontend, size:S, lgtm

#2106 fix(frontend): prevent closing eval-config modal when click outside
  agenta-web/src/components/pages/evaluations/autoEvaluation/EvaluatorsModal/EvaluatorsModal.tsx
Labels: bug, Frontend, size:XS, lgtm

#2102 [UI]: implement test sets main view
  agenta-backend/agenta_backend/models/api/testset_model.py
  agenta-backend/agenta_backend/routers/testset_router.py
  agenta-web/cypress/e2e/single-model-test-evaluation.cy.ts
  agenta-web/cypress/e2e/testset.cy.ts
  agenta-web/cypress/support/commands/evaluations.ts
  agenta-web/public/assets/not-found.png
  agenta-web/src/components/DynamicCodeBlock/CodeBlock.tsx
  agenta-web/src/components/NoResultsFound/NoResultsFound.tsx
  agenta-web/src/components/TestSetTable/TableHeaderComponent.tsx
  agenta-web/src/components/TestSetTable/TestsetTable.tsx
  agenta-web/src/components/pages/testset/modals/CreateTestset.tsx
  agenta-web/src/components/pages/testset/modals/CreateTestsetFromApi.tsx
  agenta-web/src/components/pages/testset/modals/CreateTestsetFromScratch.tsx
  agenta-web/src/components/pages/testset/modals/UploadTestset.tsx
  agenta-web/src/components/pages/testset/modals/index.tsx
  agenta-web/src/lib/Types.ts
  agenta-web/src/pages/apps/[app_id]/testsets/index.tsx
  agenta-web/src/pages/apps/[app_id]/testsets/new/api/index.tsx
  agenta-web/src/pages/apps/[app_id]/testsets/new/endpoint/index.tsx
  agenta-web/src/pages/apps/[app_id]/testsets/new/manual/index.tsx
  agenta-web/src/pages/apps/[app_id]/testsets/new/upload/index.tsx
  agenta-web/src/services/testsets/api/index.ts
Labels: UI, size:XXL, lgtm

#2112 docs(app): Prompt mangement + Restructuring + Miscs
  docs/README.md
  docs/docs/concepts/01-concepts.mdx
  docs/docs/concepts/02-architecture.mdx
  docs/docs/evaluation/01-overview.mdx
  docs/docs/evaluation/03-configure-evaluators.mdx
  docs/docs/evaluation/04-no-code-evaluation.mdx
  docs/docs/evaluation/05-sdk-evaluation.mdx
  docs/docs/getting-started/01-introduction.mdx
  docs/docs/getting-started/02-quick-start.mdx
  docs/docs/guides/cookbooks/evaluations_with_sdk.mdx
  docs/docs/prompt-management/01-overview.mdx
  docs/docs/prompt-management/02-quick-start.mdx
  docs/docs/prompt-management/03-creating-a-custom-template.mdx
  docs/docs/prompt-management/04-using-the-playground.mdx
  docs/docs/prompt-management/integration/01-how-to-integrate-with-agenta.mdx
  docs/docs/prompt-management/integration/02-fetch-prompts.mdx
  docs/docs/prompt-management/integration/03-proxy-calls.mdx
  docs/docs/prompt-management/integration/_category_.json
  docs/docs/prompt_management/01-concepts.mdx
  docs/docs/prompt_management/02-creating-a-prompt.mdx
  docs/docs/prompt_management/05-publishing-changes.mdx
  docs/docs/prompt_management/06-integrating-with-agenta.mdx
  docs/docusaurus.config.ts
  docs/sidebars.ts
  docs/src/css/custom.css
  docs/static/images/agenta-cover.png
  docs/static/images/agenta_mockup_blackbg.png
  docs/static/images/agenta_mockup_grey_bg.png
  docs/static/images/agenta_mockup_whitebg.png
  docs/static/images/evaluation/evaluate-sdk.png
  docs/static/images/evaluation/evaluation-sdk-fig.png
  docs/static/images/evaluation/evaluator-mapping.png
  docs/static/images/evaluation/evaluator_config_mapping.png
  docs/static/images/evaluation/evaluators-inout.png
  docs/static/images/evaluation/evaluators.png
  docs/static/images/prompt_management/as-a-prompt-management.png
  docs/static/images/prompt_management/as-a-proxy.png
  docs/static/images/prompt_management/asapromptmanagement.png
  docs/static/images/prompt_management/asaproxy.png
  docs/static/images/prompt_management/call-prompt.gif
  docs/static/images/prompt_management/create-prompt-modal.png
  docs/static/images/prompt_management/deploy-action.png
  docs/static/images/prompt_management/deployment-modal.png
  docs/static/images/prompt_management/illustration-llmops.png
  docs/static/images/prompt_management/llm_lifecycle.png
  docs/static/images/prompt_management/revert-deployment.png
  docs/static/images/prompt_management/taxonomy-concepts.png
  docs/static/images/prompt_management/taxonomy_agenta.png
Labels: documentation, size:XL, lgtm

#2084 [Docs] Changelog Evaluator Debugging
  docs/blog/main.mdx
  docs/package-lock.json
  docs/package.json
Labels: documentation, size:S, lgtm

#2117 [Bug Fix]: agenta CLI does not work anymore post-release (project structure)
  agenta-backend/agenta_backend/routers/app_router.py
  agenta-backend/agenta_backend/routers/variants_router.py
  agenta-backend/agenta_backend/services/app_manager.py
Labels: bug, CLI, size:S, lgtm

#2121 fix(doc): fixed all broken links
  docs/blog/main.mdx
  docs/docs/evaluation/evaluators/05-rag-evaluators.mdx
  docs/docs/getting-started/01-introduction.mdx
  docs/docs/getting-started/02-quick-start.mdx
  docs/docs/prompt-management/01-overview.mdx
  docs/docs/prompt-management/02-quick-start.mdx
  docs/docs/prompt-management/03-creating-a-custom-template.mdx
  docs/docs/prompt-management/integration/01-how-to-integrate-with-agenta.mdx
  docs/docs/reference/api/agenta-backend.info.mdx
  docs/docs/self-host/deploy_remotly/host-on-gcp.mdx
  docs/docusaurus.config.ts
Labels: documentation, size:M, lgtm

#2120 fix(frontend): converted all the buttons to it's default size in app overview page
  agenta-web/src/components/HumanEvaluations/AbTestingEvaluation.tsx
  agenta-web/src/components/HumanEvaluations/SingleModelEvaluation.tsx
  agenta-web/src/components/pages/overview/automaticEvaluation/AutomaticEvalOverview.tsx
  agenta-web/src/components/pages/overview/deployments/DeploymentOverview.tsx
  agenta-web/src/components/pages/overview/variants/VariantsOverview.tsx
  agenta-web/src/pages/apps/[app_id]/overview/index.tsx
Labels: Frontend, size:M, lgtm

#2114 [Doc]: implemented ideal-image plugin
  docs/blog/main.mdx
  docs/docs/concepts/01-concepts.mdx
  docs/docs/concepts/02-architecture.mdx
  docs/docs/evaluation/02-create-test-sets.mdx
  docs/docs/evaluation/03-configure-evaluators.mdx
  docs/docs/evaluation/04-no-code-evaluation.mdx
  docs/docs/evaluation/05-sdk-evaluation.mdx
  docs/docs/evaluation/06-human_evaluation.mdx
  docs/docs/evaluation/evaluators/05-rag-evaluators.mdx
  docs/docs/getting-started/01-introduction.mdx
  docs/docs/getting-started/02-quick-start.mdx
  docs/docs/guides/tutorials/build-rag-application.mdx
  docs/docs/misc/contributing/file-issue.mdx
  docs/docs/misc/team_management.mdx
  docs/docs/prompt-management/01-overview.mdx
  docs/docs/prompt-management/02-quick-start.mdx
  docs/docs/prompt-management/04-using-the-playground.mdx
  docs/docs/prompt-management/integration/01-how-to-integrate-with-agenta.mdx
  docs/docs/prompt-management/integration/03-proxy-calls.mdx
  docs/docs/self-host/deploy_remotly/host-on-gcp.mdx
  docs/docusaurus.config.ts
  docs/package-lock.json
  docs/package.json
Labels: documentation, size:L, lgtm

#2122 enhance(doc): enabled broken link detector
  docs/docs/misc/contributing/getting-started.mdx
  docs/docusaurus.config.ts
Labels: documentation, size:XS, lgtm

#2116 fix(frontend): added export button on evaluation
  agenta-web/src/components/HumanEvaluations/AbTestingEvaluation.tsx
  agenta-web/src/components/HumanEvaluations/SingleModelEvaluation.tsx
  agenta-web/src/components/pages/evaluations/autoEvaluation/AutoEvaluation.tsx
  agenta-web/src/lib/helpers/evaluate.ts
Labels: Frontend, UI, size:L, lgtm

#2111 fix(frontend): moved testset out of application scope
  agenta-web/cypress/e2e/eval.evaluations.cy.ts
  agenta-web/cypress/e2e/single-model-test-evaluation.cy.ts
  agenta-web/cypress/e2e/testset.cy.ts
  agenta-web/cypress/support/commands/evaluations.ts
  agenta-web/src/components/HumanEvaluations/AbTestingEvaluation.tsx
  agenta-web/src/components/HumanEvaluations/SingleModelEvaluation.tsx
  agenta-web/src/components/Sidebar/config.tsx
  agenta-web/src/components/TestSetTable/TestsetTable.tsx
  agenta-web/src/components/pages/evaluations/autoEvaluation/AutoEvaluation.tsx
  agenta-web/src/components/pages/evaluations/evaluationCompare/EvaluationCompare.tsx
  agenta-web/src/components/pages/evaluations/evaluationScenarios/EvaluationScenarios.tsx
  agenta-web/src/components/pages/overview/automaticEvaluation/AutomaticEvalOverview.tsx
  agenta-web/src/components/pages/testset/modals/CreateTestsetFromApi.tsx
  agenta-web/src/components/pages/testset/modals/CreateTestsetFromScratch.tsx
  agenta-web/src/components/pages/testset/modals/UploadTestset.tsx
  agenta-web/src/components/pages/testset/modals/index.tsx
  agenta-web/src/lib/helpers/evaluate.ts
  agenta-web/src/pages/apps/testsets/[testset_id]/index.tsx
  agenta-web/src/pages/apps/testsets/index.tsx
  agenta-web/src/services/testsets/api/index.ts
Labels: bug, Frontend, size:L, lgtm

#2108 fix(frontend): padding issue in workspace selector component
  agenta-web/src/components/Sidebar/Sidebar.tsx
Labels: bug, size:S, lgtm

#2124 [Bug Fix]: Filter environment revisions by ascending order
  agenta-backend/agenta_backend/services/db_manager.py
Labels: bug, Backend, size:XS, lgtm

#2125 Move templates to backend
  agenta-backend/agenta_backend/migrations/mongo_to_postgres/docker-compose.migration.yml
  agenta-backend/agenta_backend/resources/templates/templates.py
  agenta-backend/agenta_backend/services/templates_manager.py
  docker-compose.gh.yml
  docker-compose.prod.yml
  docker-compose.test.yml
  docker-compose.yml
Labels: Backend, size:M, lgtm

#2129 fix(frontend): font style issue
  agenta-web/src/components/Layout/ThemeContextProvider.tsx
  agenta-web/src/styles/tokens/antd-themeConfig.json
Labels: bug, Frontend, antd, size:L, lgtm

#2132 [Bug Fix]: Resolve keyword argument error when deleting human evaluation after KeyError in annotation creation
  agenta-backend/agenta_backend/services/evaluation_service.py
Labels: bug, size:XS, lgtm

#2127 [Enhancement]: Remove Pydantic warnings in CLI
  agenta-cli/agenta/client/backend/core/pydantic_utilities.py
Labels: enhancement, CLI, size:XS, lgtm

#2133 [Enhancement]: Improve custom code evaluation sandbox
  agenta-backend/agenta_backend/services/security/sandbox.py
Labels: enhancement, size:M, lgtm

#2035 [Fix]: Raise NoResultFound Exception for Missing Base
  agenta-backend/agenta_backend/routers/container_router.py
  agenta-backend/agenta_backend/services/db_manager.py
Labels: bug, Backend, size:M, lgtm

#2134 Dependabot PRs merged into one
  agenta-cli/poetry.lock
Labels: dependencies, size:XS, lgtm

#2136 Hot fix container_router
  agenta-backend/agenta_backend/routers/container_router.py
Labels: bug, size:M, lgtm

#2092 [UI]: implemented app management view
  agenta-web/cypress/support/commands/evaluations.ts
  agenta-web/public/assets/dark-complete-transparent_white_logo.png
  agenta-web/src/components/AppSelector/AppCard.tsx
  agenta-web/src/components/AppSelector/AppSelector.tsx
  agenta-web/src/components/AppSelector/AppTemplateCard.tsx
  agenta-web/src/components/AppSelector/Welcome.tsx
  agenta-web/src/components/AppSelector/modals/AddAppFromTemplateModal.tsx
  agenta-web/src/components/AppSelector/modals/AddNewAppModal.tsx
  agenta-web/src/components/AppSelector/modals/CreateAppStatusModal.tsx
  agenta-web/src/components/AppSelector/modals/CustomAppCreationLoader.tsx
  agenta-web/src/components/AppSelector/modals/EditAppModal.tsx
  agenta-web/src/components/AppSelector/modals/MaxAppModal.tsx
  agenta-web/src/components/AppSelector/modals/WriteOwnAppModal.tsx
  agenta-web/src/styles/globals.css
Labels: UI, size:XXL, lgtm

#2143 E2e tests
  .github/workflows/run-e2e-tests.yml
Labels: tests, size:XS, lgtm

#2144 docs(app): changelog 0.26
  docs/blog/main.mdx
Labels: documentation, size:M, lgtm

#2150 test(frontend): fixed e2e test fails
  agenta-web/cypress/support/commands/evaluations.ts
Labels: Frontend, tests, size:XS, lgtm

#2103 feature(frontend): Implement observability view
  agenta-web/package-lock.json
  agenta-web/package.json
  agenta-web/src/components/CopyButton/CopyButton.tsx
  agenta-web/src/components/Filters/EditColumns.tsx
  agenta-web/src/components/Filters/Filters.tsx
  agenta-web/src/components/Filters/Sort.tsx
  agenta-web/src/components/GenericDrawer/index.tsx
  agenta-web/src/components/ResultTag/ResultTag.tsx
  agenta-web/src/components/Sidebar/config.tsx
  agenta-web/src/components/pages/observability/components/AccordionTreePanel.tsx
  agenta-web/src/components/pages/observability/components/AvatarTreeContent.tsx
  agenta-web/src/components/pages/observability/components/DeleteTraceModal.tsx
  agenta-web/src/components/pages/observability/components/StatusRenderer.tsx
  agenta-web/src/components/pages/observability/drawer/TraceContent.tsx
  agenta-web/src/components/pages/observability/drawer/TraceHeader.tsx
  agenta-web/src/components/pages/observability/drawer/TraceTree.tsx
  agenta-web/src/components/pages/overview/variants/VariantDrawer.tsx
  agenta-web/src/contexts/observability.context.tsx
  agenta-web/src/lib/Types.ts
  agenta-web/src/lib/helpers/observability_helpers.ts
  agenta-web/src/pages/apps/[app_id]/observability/index.tsx
  agenta-web/src/services/observability/api/index.ts
  agenta-web/src/services/observability/core/index.ts
  agenta-web/src/services/observability/types/index.ts
Labels: Frontend, feature, typescript, size:XXL, lgtm

#2158 fix(frontend): observability status render issue
  agenta-web/src/components/pages/observability/components/StatusRenderer.tsx
Labels: bug, UI, size:S, lgtm

#2162 (frontend)[1180]: Popover in observability table take sometimes too long to appear
  agenta-web/src/pages/apps/[app_id]/observability/index.tsx
Labels: Frontend, UX, size:S, lgtm

#2160 fix(frontend): observability LLM traceTab issue
  agenta-web/src/pages/apps/[app_id]/observability/index.tsx
Labels: bug, Frontend, size:XS, lgtm

#2159 (frontend)[Age 1177]: Delete trace functionality does not work
  agenta-web/src/components/pages/observability/components/DeleteTraceModal.tsx
  agenta-web/src/components/pages/observability/drawer/TraceHeader.tsx
  agenta-web/src/services/observability/core/index.ts
Labels: bug, Frontend, size:M, lgtm
