Repository Agenta-AI/agenta, pull requests merged in 2024-08, with the labels that each got.

#1856 Feat: add Alembic support for database migration
  .github/workflows/run-backend-tests.yml
  .github/workflows/run-frontend-tests.yml
  agenta-backend/Dockerfile
  agenta-backend/agenta_backend/main.py
  agenta-backend/agenta_backend/migrations/postgres/README.md
  agenta-backend/agenta_backend/migrations/postgres/alembic.oss.ini
  agenta-backend/agenta_backend/migrations/postgres/env.py
  agenta-backend/agenta_backend/migrations/postgres/script.py.mako
  agenta-backend/agenta_backend/migrations/postgres/utils.py
  agenta-backend/agenta_backend/migrations/postgres/versions/b80c708c21bb_initial_migration.py
  agenta-backend/agenta_backend/models/db/config.py
  agenta-backend/agenta_backend/models/db/models.py
  agenta-backend/agenta_backend/models/db/postgres_engine.py
  agenta-backend/agenta_backend/models/db_engine.py
  agenta-backend/agenta_backend/services/app_manager.py
  agenta-backend/agenta_backend/services/db_manager.py
  agenta-backend/agenta_backend/services/evaluation_service.py
  agenta-backend/agenta_backend/services/user_service.py
  agenta-backend/agenta_backend/tasks/evaluations.py
  agenta-backend/agenta_backend/tests/conftest.py
  agenta-backend/agenta_backend/tests/engine.py
  agenta-backend/agenta_backend/tests/unit/test_evaluators.py
  agenta-backend/agenta_backend/tests/variants_main_router/conftest.py
  agenta-backend/agenta_backend/tests/variants_main_router/test_app_variant_router.py
  agenta-backend/agenta_backend/tests/variants_main_router/test_variant_evaluators_router.py
  agenta-backend/agenta_backend/tests/variants_main_router/test_variant_testset_router.py
  agenta-backend/agenta_backend/tests/variants_main_router/test_variant_versioning_deployment.py
  agenta-backend/agenta_backend/tests/variants_user_profile_router/test_user_profile.py
  agenta-backend/poetry.lock
  agenta-backend/pyproject.toml
  agenta-backend/start_server.sh
  docker-compose.gh.yml
  docker-compose.prod.yml
  docker-compose.test.yml
  docker-compose.yml
  docs/self-host/migration/applying-schema-migration.mdx
Labels: enhancement, Backend, size:XXL, lgtm

#1960 Rag with poetry lock from main
  agenta-backend/poetry.lock
  agenta-backend/pyproject.toml
Labels: size:XS

#1963 fix(sdk): AGE-504 Fix Tracing with LiteLLM
  agenta-cli/agenta/sdk/decorators/llm_entrypoint.py
  agenta-cli/agenta/sdk/tracing/callbacks.py
  agenta-cli/agenta/sdk/tracing/llm_tracing.py
  agenta-cli/agenta/sdk/tracing/tracing_context.py
Labels: bug, CLI, SDK, size:L, lgtm

#1967 fix (workflow): replace deprecated 'docker-compose' command in test workflow
  .github/workflows/run-backend-tests.yml
  .github/workflows/run-frontend-tests.yml
Labels: bug, Frontend, Backend, size:XS, lgtm

#1966 [Enhancement] Enable automatic migration for first-time users and optionally for returning users
  .github/workflows/run-backend-tests.yml
  .github/workflows/run-frontend-tests.yml
  agenta-backend/agenta_backend/migrations/postgres/README.md
  agenta-backend/agenta_backend/migrations/postgres/utils.py
  docker-compose.gh.yml
  docker-compose.prod.yml
  docker-compose.test.yml
  docker-compose.yml
  docs/self-host/migration/applying-schema-migration.mdx
Labels: documentation, enhancement, Backend, size:L, lgtm

#1971 fix: docker-compose.gh.yml
  docker-compose.gh.yml
Labels: devops, size:XS, lgtm

#1968 fix(tool): AGE-512 fix issues in postgres container
  docker-assets/postgres/init-db.sql
  docker-compose.gh.yml
  docker-compose.prod.yml
  docker-compose.test.yml
  docker-compose.yml
Labels: bug, size:M, lgtm

#1941 Improve description Json diff eval and fix minor issue
  agenta-backend/agenta_backend/resources/evaluators/evaluators.py
  agenta-backend/agenta_backend/services/evaluators_service.py
Labels: bug, Backend, size:S, lgtm

#1953 Fix: human evaluation tests syntax error
  agenta-web/src/lib/helpers/utils.ts
Labels: bug, Frontend, typescript, size:XS, lgtm

#1981 Test: modify single model evaluation scores
  agenta-web/cypress/e2e/single-model-test-evaluation.cy.ts
  agenta-web/src/components/Evaluations/AutomaticEvaluationResult.tsx
Labels: Frontend, typescript, cypress, size:S, lgtm

#1979 Test: upload testset as csv
  agenta-web/cypress/e2e/testset.cy.ts
  agenta-web/src/pages/apps/[app_id]/testsets/new/upload/index.tsx
Labels: Frontend, tests, typescript, cypress, size:M, lgtm

#1990 fix(backend): fix json evaluator description
  agenta-backend/agenta_backend/resources/evaluators/evaluators.py
Labels: bug, Backend, python, size:XS, lgtm

#1980 Test: save single model testset
  agenta-web/cypress/e2e/single-model-test-evaluation.cy.ts
  agenta-web/src/components/EvaluationTable/SingleModelEvaluationTable.tsx
  agenta-web/src/components/SaveTestsetModal/SaveTestsetModal.tsx
Labels: Frontend, tests, cypress, size:S, lgtm

#1991 [Enhancement]: added modification information for variant
  agenta-backend/agenta_backend/models/api/api_models.py
  agenta-backend/agenta_backend/models/converters.py
  agenta-backend/agenta_backend/services/db_manager.py
  agenta-cli/agenta/client/backend/types/app_variant_response.py
Labels: enhancement, Backend, size:M, lgtm

#1992 fix(tool): AGE-612 fix dependencies with langchain_community
  examples/chat_models/app.py
  examples/chat_models/requirements.txt
Labels: bug, dependencies, size:S, lgtm

#1961 AGE 486 - SDK v3 - Configuration management with Pydantic
  .gitignore
  agenta-cli/agenta/__init__.py
  agenta-cli/agenta/docker/docker_utils.py
  agenta-cli/agenta/sdk/__init__.py
  agenta-cli/agenta/sdk/assets.py
  agenta-cli/agenta/sdk/config_manager.py
  agenta-cli/agenta/sdk/decorators/llm_entrypoint.py
  agenta-cli/agenta/sdk/types.py
  agenta-cli/agenta/sdk/utils/__init__.py
  agenta-cli/poetry.lock
  agenta-cli/pyproject.toml
  agenta-cli/tests/management_sdk/manual_tests/apps_with_new_sdk/new_baby_name.py
  agenta-cli/tests/management_sdk/manual_tests/apps_with_new_sdk/new_chat_prompt.py
  agenta-cli/tests/management_sdk/manual_tests/apps_with_new_sdk/new_single_prompt.py
  agenta-cli/tests/management_sdk/manual_tests/apps_with_new_sdk/requirements.txt
  agenta-cli/tests/management_sdk/manual_tests/apps_with_new_sdk/run_local.py
  agenta-cli/tests/management_sdk/manual_tests/apps_with_new_sdk/v3.py
  agenta-cli/tests/management_sdk/manual_tests/apps_with_old_sdk/baby_name.py
  agenta-cli/tests/management_sdk/manual_tests/apps_with_old_sdk/chat_prompt.py
  agenta-cli/tests/management_sdk/manual_tests/apps_with_old_sdk/requirements.txt
  agenta-cli/tests/management_sdk/manual_tests/apps_with_old_sdk/run_local.py
  agenta-cli/tests/management_sdk/manual_tests/apps_with_old_sdk/single_prompt.py
  agenta-cli/tests/management_sdk/run_local.py
  agenta-cli/tests/management_sdk/test_config_manager.py
  agenta-cli/tests/management_sdk/v1.py
  agenta-cli/tests/management_sdk/v2.py
  agenta-cli/tests/management_sdk/v4_prompt.py
Labels: enhancement, Frontend, example, CLI, SDK, size:XXL, lgtm

#1938 feat(backend): AGE-276 and AGE-471 Improves LLM-as-a-judge reliability
  agenta-backend/agenta_backend/resources/evaluators/evaluators.py
  agenta-backend/agenta_backend/services/evaluators_service.py
Labels: enhancement, Backend, size:XS, lgtm

#1998 [Bug Fix]: enhance image validation and app variant update logic for cloud-dev environment
  agenta-backend/agenta_backend/services/db_manager.py
  agenta-backend/agenta_backend/services/deployment_manager.py
Labels: bug, Backend, size:S, lgtm

#1995 [Enhancement]: Implemented endpoint for renaming an application
  agenta-backend/agenta_backend/models/api/api_models.py
  agenta-backend/agenta_backend/routers/app_router.py
  agenta-backend/agenta_backend/services/db_manager.py
  agenta-backend/agenta_backend/tests/variants_main_router/test_app_variant_router.py
Labels: enhancement, Backend, tests, size:L, lgtm

#2000 fix(frontend) BaseResponse in WebUI when dict-style
  agenta-web/src/lib/helpers/utils.ts
Labels: bug, Frontend, size:XS, lgtm

#2001 fix(backend) json-diff evaluator
  agenta-backend/agenta_backend/services/evaluators_service.py
  agenta-backend/agenta_backend/tests/unit/test_evaluators.py
Labels: bug, Backend, size:M, lgtm

#1986 design(frontend): AGE-513 Implement Overview and App management view
  agenta-backend/agenta_backend/models/api/api_models.py
  agenta-backend/agenta_backend/models/api/user_models.py
  agenta-backend/agenta_backend/models/converters.py
  agenta-backend/agenta_backend/routers/user_profile.py
  agenta-backend/agenta_backend/services/db_manager.py
  agenta-backend/agenta_backend/tests/variants_user_profile_router/test_user_profile.py
  agenta-cli/agenta/client/backend/types/app_variant_response.py
  agenta-web/cypress.config.ts
  agenta-web/cypress/e2e/eval.comparison.cy.ts
  agenta-web/cypress/e2e/eval.evaluations.cy.ts
  agenta-web/cypress/e2e/eval.scenarios.cy.ts
  agenta-web/cypress/e2e/playground.cy.ts
  agenta-web/cypress/support/commands/evaluations.ts
  agenta-web/package-lock.json
  agenta-web/package.json
  agenta-web/public/assets/slack.png
  agenta-web/src/components/AppSelector/AppCard.tsx
  agenta-web/src/components/AppSelector/AppSelector.tsx
  agenta-web/src/components/AppSelector/modals/DeleteAppModal.tsx
  agenta-web/src/components/DeleteEvaluationModal/DeleteEvaluationModal.tsx
  agenta-web/src/components/Evaluations/AutomaticEvaluationResult.tsx
  agenta-web/src/components/Evaluations/EvaluationCardView/EvaluationVotePanel.tsx
  agenta-web/src/components/Evaluations/HumanEvaluationResult.tsx
  agenta-web/src/components/HumanEvaluationModal/HumanEvaluationModal.tsx
  agenta-web/src/components/Layout/Layout.tsx
  agenta-web/src/components/Layout/ThemeContextProvider.tsx
  agenta-web/src/components/Playground/Views/ParametersCards.tsx
  agenta-web/src/components/Sidebar/Sidebar.tsx
  agenta-web/src/components/Sidebar/config.tsx
  agenta-web/src/components/TestSetTable/TestsetTable.tsx
  agenta-web/src/components/pages/evaluations/evaluationResults/EvaluationResults.tsx
  agenta-web/src/components/pages/overview/abTestingEvaluation/AbTestingEvalOverview.tsx
  agenta-web/src/components/pages/overview/automaticEvaluation/AutomaticEvalOverview.tsx
  agenta-web/src/components/pages/overview/automaticEvaluation/StatusRenderer.tsx
  agenta-web/src/components/pages/overview/deployments/ChangeVariantModal.tsx
  agenta-web/src/components/pages/overview/deployments/DeploymentDrawer.tsx
  agenta-web/src/components/pages/overview/deployments/DeploymentModal.tsx
  agenta-web/src/components/pages/overview/deployments/DeploymentOverview.tsx
  agenta-web/src/components/pages/overview/singleModelEvaluation/SingleModelEvalOverview.tsx
  agenta-web/src/components/pages/overview/variants/DeployVariantModal.tsx
  agenta-web/src/components/pages/overview/variants/VariantComparisonModal.tsx
  agenta-web/src/components/pages/overview/variants/VariantDrawer.tsx
  agenta-web/src/components/pages/overview/variants/VariantPopover.tsx
  agenta-web/src/components/pages/overview/variants/VariantsOverview.tsx
  agenta-web/src/contexts/app.context.tsx
  agenta-web/src/hooks/useQuery.ts
  agenta-web/src/lib/Types.ts
  agenta-web/src/lib/helpers/dateTimeHelper.ts
  agenta-web/src/lib/helpers/utils.ts
  agenta-web/src/lib/transformers.ts
  agenta-web/src/pages/_app.tsx
  agenta-web/src/pages/apps/[app_id]/annotations/human_a_b_testing.tsx
  agenta-web/src/pages/apps/[app_id]/endpoints/index.tsx
  agenta-web/src/pages/apps/[app_id]/overview/index.tsx
  agenta-web/src/services/api.ts
  agenta-web/src/styles/tokens/antd-themeConfig.json
Labels: Frontend, UI, UX, size:XXL, lgtm

#2010 fix(frontend): Refactor getStringOrJson function to simplify value handling
  agenta-web/src/components/Playground/Views/TestView.tsx
  agenta-web/src/lib/helpers/utils.ts
Labels: Frontend, refactoring, size:S, lgtm

#2016 fix(frontend): Migrate Inter Font to @next/font
  agenta-web/src/pages/_app.tsx
  agenta-web/src/styles/tokens/antd-themeConfig.json
Labels: Frontend, UI, size:L, lgtm

#2015 Fix FuncResponse/BaseResponse in human evaluation views
  agenta-web/src/components/EvaluationTable/ABTestingEvaluationTable.tsx
  agenta-web/src/components/EvaluationTable/SingleModelEvaluationTable.tsx
Labels: bug, Frontend, size:S, lgtm

#1987 [Enhancement]: Handle non-string outputs gracefully in auto_contains_json evaluator
  agenta-backend/agenta_backend/routers/evaluators_router.py
  agenta-backend/agenta_backend/services/evaluators_service.py
  agenta-backend/agenta_backend/tests/unit/test_evaluators.py
  agenta-cli/agenta/sdk/decorators/llm_entrypoint.py
  agenta-cli/pyproject.toml
  agenta-web/src/pages/_app.tsx
  agenta-web/src/styles/tokens/antd-themeConfig.json
Labels: enhancement, Backend, size:L, lgtm

#2012 Doc: new documentation custom style
  website/README.md
  website/blog/main.mdx
  website/docs/getting_started/introduction.mdx
  website/docs/getting_started/quick-start.mdx
  website/docs/prompt_management/integrating.mdx
  website/docs/prompt_management/setting_up/creating_an_app.mdx
  website/docs/prompt_management/setting_up/custom_applications.mdx
  website/docs/prompt_management/setting_up/using_agenta_from_cli.mdx
  website/docs/self-host/deploy_remotly/host-on-aws.mdx
  website/docs/self-host/deploy_remotly/host-on-gcp.mdx
  website/docs/self-host/migration/applying-schema-migration.mdx
  website/docusaurus.config.ts
  website/sidebars.ts
  website/src/css/custom.css
  website/static/images/dark-complete-transparent-CROPPED.png
Labels: documentation, size:XL, lgtm

#2011 feat(frontend): Implement Feature to Rename App
  agenta-web/src/components/AppSelector/AppCard.tsx
  agenta-web/src/components/AppSelector/modals/EditAppModal.tsx
  agenta-web/src/pages/apps/[app_id]/overview/index.tsx
  agenta-web/src/services/app-selector/api/index.ts
Labels: Frontend, feature, size:L, lgtm

#2021 Bump version enhancement
  .github/workflows/bump-versions.yml
Labels: ci/cd, size:M

#2018 add linting for website scripts
  .github/workflows/check-python-code-black.yml
  website/scripts/generate_cookbooks.py
Labels: ci/cd, size:S

#2024 Doc: added posthog for tracking
  website/docusaurus.config.ts
  website/package-lock.json
  website/package.json
  website/src/css/custom.css
Labels: documentation, Frontend, size:M, lgtm

#2025 [Bug Fix]: Correct permission naming from 'UPDATE_APPLICATION' to 'EDIT_APPLICATION'
  agenta-backend/agenta_backend/routers/app_router.py
Labels: bug, Backend, size:XS, lgtm

#2026 Doc: fixed posthog connectivity
  website/docusaurus.config.ts
Labels: bug, documentation, size:XS, lgtm

#2028 Doc: fixed heading wrong placement
  website/docs/evaluation/test_sets.mdx
  website/docs/observability/quickstart.mdx
  website/docs/prompt_management/integrating.mdx
  website/docs/reference/cli/core_commands/init.mdx
  website/docs/reference/cli/core_commands/variant_list.mdx
  website/docs/reference/cli/core_commands/variant_remove.mdx
  website/docs/reference/cli/core_commands/variant_serve.mdx
Labels: documentation, size:S, lgtm

#2031 Update pyproject.toml
  agenta-cli/pyproject.toml
Labels: CLI, size:XS, lgtm

#2032 Update posthog parameter for docs
  website/docusaurus.config.ts
Labels: size:XS

#2033 Fix configs for docs to go to production
  website/docusaurus.config.ts
Labels: documentation, size:S

#1989 [Enhancement] Add LLM API key checks to LLM-based evaluators
  agenta-backend/agenta_backend/resources/evaluators/evaluators.py
  agenta-backend/agenta_backend/routers/evaluation_router.py
  agenta-backend/agenta_backend/services/db_manager.py
  agenta-backend/agenta_backend/services/evaluator_manager.py
  agenta-backend/agenta_backend/services/evaluators_service.py
  agenta-backend/agenta_backend/services/helpers.py
  agenta-backend/agenta_backend/tests/unit/test_evaluators.py
  agenta-backend/agenta_backend/tests/variants_main_router/conftest.py
  agenta-backend/agenta_backend/tests/variants_main_router/test_variant_evaluators_router.py
  agenta-backend/agenta_backend/tests/variants_user_profile_router/test_user_profile.py
Labels: enhancement, Backend, size:L, lgtm

#2023 [Feature]: Added logic for tracking application last modified by
  agenta-backend/agenta_backend/migrations/postgres/versions/5c29a64204f4_added_modified_by_id_column_to_apps_db.py
  agenta-backend/agenta_backend/models/api/api_models.py
  agenta-backend/agenta_backend/models/converters.py
  agenta-backend/agenta_backend/models/db_models.py
  agenta-backend/agenta_backend/routers/environment_router.py
  agenta-backend/agenta_backend/routers/evaluation_router.py
  agenta-backend/agenta_backend/routers/evaluators_router.py
  agenta-backend/agenta_backend/routers/human_evaluation_router.py
  agenta-backend/agenta_backend/routers/variants_router.py
  agenta-backend/agenta_backend/services/app_manager.py
  agenta-backend/agenta_backend/services/db_manager.py
  agenta-web/src/components/AppSelector/AppCard.tsx
  agenta-web/src/lib/Types.ts
Labels: Frontend, Backend, feature, size:L, lgtm

#2013 [Enhancement]: Improve pending migration(s) check
  agenta-backend/agenta_backend/migrations/postgres/utils.py
Labels: enhancement, Backend, size:M, lgtm

#2034 Update getting_support.mdx
  website/docs/misc/getting_support.mdx
Labels: documentation, size:S

#2036 Agenta readme broken link fix
  README.md
  agenta-cli/README.md
Labels: documentation, size:M, lgtm

#2039 Links update
  CONTRIBUTING.md
Labels: documentation, size:XS, lgtm

#2041 Mmabrouk/docs/AGE-732-changelog-update
  website/blog/main.mdx
  website/docusaurus.config.ts
  website/static/images/changelog/configure_expected_answer.png
  website/static/images/changelog/export_evaluation.png
  website/static/images/changelog/new_ui.png
  website/static/images/changelog/rag_faithfulness.png
  website/static/images/changelog/trace_in_playground.png
Labels: documentation, UI, size:XL

#2046 Fix links in docs
  docs/docs/guides/tutorials/list_templates.mdx
  docs/docs/misc/contributing/getting-started.mdx
  docs/docusaurus.config.ts
Labels: documentation, size:M

#2048 added analytics to docs
  docs/docusaurus.config.ts
  docs/static/ga-script.js
  docs/static/hotjar.js
Labels: documentation, size:S

#2049 typo fix in rag
  docs/docs/evaluation/rag_evaluators.mdx
Labels: documentation, size:M
