Repository Agenta-AI/agenta, pull requests merged in 2024-12, with the labels that each got.

#2331 (frontend)[AGE-1396]: Upload testset from CSV validation failing
  agenta-web/src/lib/helpers/fileManipulations.ts
Labels: bug, Frontend, size:XS

#2329 (frontend)[AGE-1398]: You should not be able to open a running evaluation
  agenta-web/src/components/pages/evaluations/autoEvaluation/AutoEvaluation.tsx
Labels: bug, size:S, lgtm

#2335 enhance(frontend)[AGE-1405]:: Replace png onboarding image in public folder with a smaller webp image
  agenta-web/public/assets/On-boarding.webp
Labels: Frontend, size:XS

#2333 Changelog 28.0
  docs/blog/main.mdx
Labels: documentation, size:S

#2328 [Feat]: implement Test set drawer UI
  agenta-web/src/components/GenericDrawer/index.tsx
  agenta-web/src/components/pages/observability/ObservabilityDashboard.tsx
  agenta-web/src/components/pages/observability/drawer/TestsetDrawer.tsx
  agenta-web/src/components/pages/observability/drawer/TraceContent.tsx
  agenta-web/src/lib/helpers/utils.ts
Labels: Frontend, UI, feature, size:XL

#2340 fix(frontend): logout button unclickable issue
  agenta-web/src/components/Sidebar/Sidebar.tsx
Labels: bug, Frontend, size:S, lgtm

#2339 [Feature]: Display a "Not Optimized for Mobile" overlay to users trying to access Agenta app from browsers with narrow width
  agenta-web/src/components/NoMobilePageWrapper/NoMobilePageWrapper.tsx
  agenta-web/src/components/NoMobilePageWrapper/assets/constants.ts
  agenta-web/src/hooks/useResizeObserver.ts
  agenta-web/src/pages/_app.tsx
Labels: UI, typescript, size:L

#2338 [Feature] Onboarding - Demos
  agenta-backend/agenta_backend/routers/projects_router.py
Labels: Backend, feature, size:XS, lgtm

#2342 [Fix] Errors in llm apps freezes the playground
  agenta-cli/agenta/sdk/decorators/routing.py
  agenta-web/src/services/api.ts
Labels: bug, size:S, lgtm

#2343 (frontend)[AGE-1415]: Update lodash imports
  agenta-web/src/components/ChatInputs/ChatInputs.tsx
  agenta-web/src/components/EvaluationTable/ABTestingEvaluationTable.tsx
  agenta-web/src/components/EvaluationTable/SingleModelEvaluationTable.tsx
  agenta-web/src/components/Evaluations/EvaluationCardView/index.tsx
  agenta-web/src/components/Filters/Filters.tsx
  agenta-web/src/components/Playground/AddToTestSetDrawer/AddToTestSetDrawer.tsx
  agenta-web/src/components/Playground/Views/TestView.tsx
  agenta-web/src/components/pages/evaluations/autoEvaluation/AutoEvaluation.tsx
  agenta-web/src/components/pages/evaluations/autoEvaluation/EvaluatorsModal/ConfigureEvaluator/Messages.tsx
  agenta-web/src/components/pages/evaluations/evaluationCompare/EvaluationCompare.tsx
  agenta-web/src/components/pages/evaluations/evaluationScenarios/EvaluationScenarios.tsx
  agenta-web/src/hooks/useDeepCompareEffect.ts
  agenta-web/src/lib/helpers/axiosConfig.ts
  agenta-web/src/lib/helpers/evaluate.ts
  agenta-web/src/lib/helpers/llmProviders.ts
  agenta-web/src/services/evaluations/api/index.ts
Labels: Frontend, size:M, lgtm

#2345 Fix pycryptodome vulnerability
  agenta-backend/agenta_backend/models/api/evaluation_model.py
  agenta-backend/agenta_backend/services/llm_apps_service.py
  agenta-backend/agenta_backend/tasks/evaluations.py
  agenta-backend/poetry.lock
  agenta-backend/pyproject.toml
Labels: dependencies, size:M

#2332 [Dependency]: Vault -- Checkpoint 1
  agenta-backend/agenta_backend/core/shared/dtos.py
  agenta-backend/agenta_backend/dbs/postgres/shared/dbas.py
Labels: Backend, size:M

#2347 Update evaluators_service.py
  agenta-backend/agenta_backend/services/evaluators_service.py
Labels: Backend, size:XS

#2348 fix(backend): fixes the debug line, fstring not working
  agenta-backend/agenta_backend/services/app_manager.py
Labels: bug, Backend, size:XS

#2354 Redirects for cli quick-usage in docs
  docs/docusaurus.config.ts
Labels: documentation, size:XS

#2346 Release/v0.28.1
  agenta-backend/agenta_backend/models/api/evaluation_model.py
  agenta-backend/agenta_backend/services/llm_apps_service.py
  agenta-backend/agenta_backend/tasks/evaluations.py
  agenta-backend/poetry.lock
  agenta-backend/pyproject.toml
  agenta-cli/pyproject.toml
  agenta-web/package-lock.json
  agenta-web/package.json
Labels: dependencies, python, size:M, lgtm

#2336 Fix pycryptodome vulnerability
  agenta-backend/agenta_backend/models/api/evaluation_model.py
  agenta-backend/agenta_backend/services/llm_apps_service.py
  agenta-backend/agenta_backend/tasks/evaluations.py
  agenta-backend/poetry.lock
  agenta-backend/pyproject.toml
Labels: Backend, dependencies, size:M

#2355 [Hotfix] Failing templates due to LiteLLM callback issues
  agenta-cli/agenta/sdk/litellm/litellm.py
  agenta-cli/agenta/sdk/tracing/inline.py
  agenta-cli/agenta/sdk/tracing/processors.py
  agenta-web/src/components/Playground/Views/TestView.tsx
Labels: SDK, size:L, lgtm

#2337 (frontend)[AGE-1393]: Update create new evaluation modal with new design
  agenta-web/cypress/e2e/eval.comparison.cy.ts
  agenta-web/cypress/e2e/eval.evaluations.cy.ts
  agenta-web/cypress/support/commands/evaluations.ts
  agenta-web/src/components/pages/evaluations/NewEvaluation/AdvancedSettingsPopover.tsx
  agenta-web/src/components/pages/evaluations/NewEvaluation/NewEvaluationModal.tsx
  agenta-web/src/components/pages/evaluations/NewEvaluation/SelectEvaluatorSection.tsx
  agenta-web/src/components/pages/evaluations/NewEvaluation/SelectTestsetSection.tsx
  agenta-web/src/components/pages/evaluations/NewEvaluation/SelectVariantSection.tsx
  agenta-web/src/components/pages/evaluations/autoEvaluation/AutoEvaluation.tsx
  agenta-web/src/components/pages/evaluations/autoEvaluation/EvaluatorsModal/EvaluatorsModal.tsx
Labels: Frontend, UI, reactjs, cypress, size:XXL, lgtm

#2349 Running Agenta on different ports
  agenta-backend/agenta_backend/services/app_manager.py
  agenta-backend/agenta_backend/services/docker_utils.py
  docker-compose.gh.yml
  docker-compose.yml
  docs/docs/self-host/host-locally.mdx
Labels: documentation, Backend, size:M

#2358 Bump pre-release
  agenta-cli/pyproject.toml
Labels: size:XS, lgtm

#2353 [Enhancement]: Display SDK Version in Deployed Applications (openapi.json)
  agenta-cli/agenta/cli/main.py
  agenta-cli/agenta/sdk/decorators/routing.py
  agenta-cli/agenta/sdk/utils/helpers.py
Labels: enhancement, CLI, SDK, size:S, lgtm

#2360 (frontend)[AGE-1461]: Window not responding after switching between workspaces while in an app
  agenta-web/src/components/Layout/Layout.tsx
Labels: bug, Frontend, size:M

#2356 (frontend)[AGE 1444]: Enhance documentation for Frontend repo, and include best practices
  agenta-web/README.md
Labels: documentation, Frontend, size:L, lgtm

#2359 Docs RAG QA
  docs/docs/tutorials/cookbooks/RAG-QA-docs.mdx
  docs/static/images/cookbooks/rag-qa-eval-config.png
  docs/static/images/cookbooks/rag-qa-playground.png
  docs/static/images/cookbooks/rag-qa-tracing.png
  examples/custom_workflows/rag-docs-qa/.env.example
  examples/custom_workflows/rag-docs-qa/README.md
  examples/custom_workflows/rag-docs-qa/generate_test_set.py
  examples/custom_workflows/rag-docs-qa/ingest.py
  examples/custom_workflows/rag-docs-qa/query.py
  examples/custom_workflows/rag-docs-qa/requirements.in
  examples/custom_workflows/rag-docs-qa/test_set.csv
  examples/custom_workflows/rag-docs-qa/test_set_small.csv
Labels: documentation, example, size:XXL

#2362 (frontend)[AGE-1464]: implement useIsomorphicLayoutEffect hook to prevent using useLayoutEffect on server
  agenta-web/src/hooks/useIsomorphicLayoutEffect.ts
  agenta-web/src/hooks/usePostHogAg.ts
Labels: Frontend, typescript, size:S, lgtm

#2368 (frontend)[AGE-1469]: Side bar spacing is wrong in small screens
  agenta-web/src/components/Sidebar/Sidebar.tsx
Labels: UI, size:XS, lgtm

#2364 (frontend)[AGE-1394]: State mix-up in create new evaluator modal
  agenta-web/src/components/pages/evaluations/autoEvaluation/EvaluatorsModal/Evaluators/index.tsx
  agenta-web/src/components/pages/evaluations/autoEvaluation/EvaluatorsModal/EvaluatorsModal.tsx
  agenta-web/src/components/pages/evaluations/autoEvaluation/EvaluatorsModal/NewEvaluator/index.tsx
Labels: bug, Frontend, size:S

#2357 (frontend)[AGE-1418]: Improve posthog initialization to reduce load on bundle size
  agenta-web/src/components/Playground/Views/ParametersView.tsx
  agenta-web/src/components/Playground/Views/PublishVariantModal.tsx
  agenta-web/src/components/pages/app-management/index.tsx
  agenta-web/src/contexts/profile.context.tsx
  agenta-web/src/hooks/usePostHogAg.ts
  agenta-web/src/hooks/useSession.ts
  agenta-web/src/lib/helpers/analytics/AgPosthogProvider.tsx
  agenta-web/src/lib/helpers/analytics/hooks/usePostHogAg.ts
  agenta-web/src/lib/helpers/analytics/store/atoms.ts
  agenta-web/src/lib/helpers/analytics/types.d.ts
  agenta-web/src/pages/_app.tsx
Labels: Frontend, size:L, lgtm

#2378 Apps running in agenta have AGENTA_RUNTIME=true
  agenta-backend/agenta_backend/services/app_manager.py
Labels: Backend, size:XS, lgtm

#2361 (frontend)[AGE-1462]: Global configuration setup for swr library
  agenta-web/src/components/HumanEvaluationModal/HumanEvaluationModal.tsx
  agenta-web/src/contexts/app.context.tsx
  agenta-web/src/lib/api/SWRConfig.tsx
  agenta-web/src/lib/api/assets/axiosConfig.ts
  agenta-web/src/lib/hooks/useVariant.ts
  agenta-web/src/pages/_app.tsx
  agenta-web/src/services/api.ts
  agenta-web/src/services/app-selector/api/index.ts
  agenta-web/src/services/deployment/api/index.ts
  agenta-web/src/services/evaluations/api/index.ts
  agenta-web/src/services/human-evaluations/api/index.ts
  agenta-web/src/services/observability/core/index.ts
  agenta-web/src/services/playground/api/index.ts
  agenta-web/src/services/project/index.ts
  agenta-web/src/services/testsets/api/index.ts
Labels: Frontend, size:L, lgtm

#2363 (frontend)[AGE-1417]: Reduce effect of AgGrid on the initial bundle size
  agenta-web/package-lock.json
  agenta-web/package.json
  agenta-web/src/components/TestSetTable/EditRowModal.tsx
  agenta-web/src/components/TestSetTable/TableCellsRenderer.tsx
  agenta-web/src/components/TestSetTable/TestsetTable.tsx
  agenta-web/src/components/pages/evaluations/FilterColumns/FilterColumns.tsx
  agenta-web/src/components/pages/evaluations/cellRenderers/cellRenderers.tsx
  agenta-web/src/components/pages/evaluations/evaluationCompare/EvaluationCompare.tsx
  agenta-web/src/components/pages/evaluations/evaluationScenarios/EvaluationScenarios.tsx
  agenta-web/src/hooks/useAgGridCustomHeaders.tsx
  agenta-web/src/lib/helpers/agGrid.tsx
  agenta-web/src/pages/_app.tsx
  agenta-web/src/pages/apps/[app_id]/evaluations/human_a_b_testing/[evaluation_id]/index.tsx
  agenta-web/src/pages/apps/[app_id]/evaluations/index.tsx
  agenta-web/src/pages/apps/[app_id]/evaluations/results/[evaluation_id]/index.tsx
  agenta-web/src/pages/apps/[app_id]/evaluations/results/compare/index.tsx
  agenta-web/src/pages/apps/[app_id]/evaluations/single_model_test/[evaluation_id]/index.tsx
  agenta-web/src/pages/testsets/[testset_id]/index.tsx
  agenta-web/src/pages/testsets/index.tsx
Labels: Frontend, size:L

#2383 Add port to README.md
  README.md
Labels: documentation, size:XS

#2352 Add pre commit hook
  .husky/pre-commit
  .husky/pre-push
  agenta-web/package-lock.json
  agenta-web/package.json
Labels: devops, size:L

#2377 (frontend)[AGE 1478]: 404 page Displays on Page Refresh Within App View
  agenta-web/cypress/e2e/eval.evaluations.cy.ts
  agenta-web/cypress/support/commands/evaluations.ts
  agenta-web/src/components/Layout/Layout.tsx
  agenta-web/src/contexts/app.context.tsx
Labels: bug, Frontend, size:S

#2170 Agenta web enhancements
  .dockerignore
  agenta-web/dev.Dockerfile
  agenta-web/next.config.js
  agenta-web/package-lock.json
  agenta-web/package.json
  agenta-web/prod.Dockerfile
  agenta-web/src/components/CardGrid/CardGrid.tsx
  agenta-web/src/components/NoMobilePageWrapper/NoMobilePageWrapper.tsx
  agenta-web/src/welcome-highlights/tip1.mdx
  agenta-web/src/welcome-highlights/tip2.mdx
Labels: Frontend, devops, typescript, size:L

#2384 fix(frontend): Fix posthog hook to keep getSurveys functionality
  agenta-web/src/lib/helpers/analytics/AgPosthogProvider.tsx
  agenta-web/src/lib/helpers/analytics/hooks/usePostHogAg.ts
Labels: bug, Frontend, size:M

#2380 (frontend)[AGE 1473]: Vault WebUI <> API Integration
  agenta-web/src/components/pages/app-management/index.tsx
  agenta-web/src/components/pages/evaluations/NewEvaluation/NewEvaluationModal.tsx
  agenta-web/src/components/pages/settings/Secrets/Secrets.tsx
  agenta-web/src/hooks/useVaultSecret.ts
  agenta-web/src/lib/helpers/dynamic.ts
  agenta-web/src/lib/helpers/llmProviders.ts
  agenta-web/src/lib/helpers/utils.ts
Labels: Frontend, size:L, lgtm

#2388 (frontend)[Age 1392]: Fix Scroll Propagation Issue in Trace Drawer with Monaco Editor
  agenta-web/src/components/pages/observability/components/AccordionTreePanel.tsx
  agenta-web/src/components/pages/observability/drawer/TraceContent.tsx
Labels: bug, Frontend, size:XS

#2386 Revert "(frontend)[AGE 1473]: Vault WebUI <> API Integration"
  agenta-web/src/components/pages/app-management/index.tsx
  agenta-web/src/components/pages/evaluations/NewEvaluation/NewEvaluationModal.tsx
  agenta-web/src/components/pages/settings/Secrets/Secrets.tsx
  agenta-web/src/hooks/useVaultSecret.ts
  agenta-web/src/lib/helpers/dynamic.ts
  agenta-web/src/lib/helpers/llmProviders.ts
  agenta-web/src/lib/helpers/utils.ts
Labels: Frontend, size:L

#2394 fix(frontend): Prevent rendering pages without required context information
  agenta-web/src/components/Layout/Layout.tsx
Labels: bug, Frontend, size:XS, lgtm

#2344 [Feature] Stateless Service
  agenta-backend/agenta_backend/routers/permissions_router.py
  agenta-cli/agenta/__init__.py
  agenta-cli/agenta/client/client.py
  agenta-cli/agenta/sdk/__init__.py
  agenta-cli/agenta/sdk/agenta_init.py
  agenta-cli/agenta/sdk/assets.py
  agenta-cli/agenta/sdk/context/exporting.py
  agenta-cli/agenta/sdk/context/routing.py
  agenta-cli/agenta/sdk/context/tracing.py
  agenta-cli/agenta/sdk/decorators/routing.py
  agenta-cli/agenta/sdk/decorators/tracing.py
  agenta-cli/agenta/sdk/managers/config.py
  agenta-cli/agenta/sdk/managers/secrets.py
  agenta-cli/agenta/sdk/middleware/auth.py
  agenta-cli/agenta/sdk/middleware/cache.py
  agenta-cli/agenta/sdk/middleware/config.py
  agenta-cli/agenta/sdk/middleware/cors.py
  agenta-cli/agenta/sdk/middleware/otel.py
  agenta-cli/agenta/sdk/middleware/vault.py
  agenta-cli/agenta/sdk/tracing/context.py
  agenta-cli/agenta/sdk/tracing/exporters.py
  agenta-cli/agenta/sdk/tracing/inline.py
  agenta-cli/agenta/sdk/tracing/processors.py
  agenta-cli/agenta/sdk/tracing/tracing.py
  agenta-cli/agenta/sdk/utils/constants.py
  agenta-cli/agenta/sdk/utils/exceptions.py
  agenta-cli/agenta/sdk/utils/globals.py
  agenta-cli/agenta/sdk/utils/timing.py
  agenta-cli/pyproject.toml
  agenta-cli/tests/baggage/_main.py
  agenta-cli/tests/baggage/agenta
  agenta-cli/tests/baggage/app.py
  agenta-cli/tests/baggage/config.toml
  agenta-cli/tests/baggage/specs/check_generate.py
  agenta-cli/tests/baggage/specs/check_openapi.py
  agenta-cli/tests/run_pytest.sh
  agenta-cli/tests/run_tests.sh
  agenta-cli/tests/start_server.sh
  agenta-cli/tests/stop_server.sh
Labels: CLI, feature, SDK, size:XXL, lgtm

#2393 (frontend)[AGE 1473]: Vault WebUI <> API Integration
  agenta-web/src/components/pages/app-management/index.tsx
  agenta-web/src/components/pages/evaluations/NewEvaluation/NewEvaluationModal.tsx
  agenta-web/src/components/pages/settings/Secrets/Secrets.tsx
  agenta-web/src/hooks/useVaultSecret.ts
  agenta-web/src/lib/helpers/dynamic.ts
  agenta-web/src/lib/helpers/llmProviders.ts
  agenta-web/src/lib/helpers/utils.ts
Labels: Frontend, size:L

#2395 (frontend)[Vault Hot Fix]: Stale secret state causing 404 when adding secrets after deletion
  agenta-web/src/components/pages/settings/Secrets/Secrets.tsx
Labels: bug, size:XS

#2391 test(frontend): hot-fix human eval fails
  agenta-web/cypress/support/commands/evaluations.ts
Labels: Frontend, tests, size:XS

#2396 Bump pre-release version & fix AttributeError for CORS
  agenta-backend/agenta_backend/models/api/evaluation_model.py
  agenta-backend/agenta_backend/routers/app_router.py
  agenta-backend/agenta_backend/services/helpers.py
  agenta-cli/agenta/client/backend/types/provider_kind.py
  agenta-cli/agenta/sdk/assets.py
  agenta-cli/agenta/sdk/decorators/routing.py
  agenta-cli/agenta/sdk/middleware/cors.py
  agenta-cli/pyproject.toml
  agenta-web/package-lock.json
  agenta-web/package.json
  agenta-web/src/hooks/useVaultSecret.ts
Labels: CLI, SDK, size:S
