Repository Agenta-AI/agenta, pull requests merged in 2024-06, with the labels that each got.

#1729 [Bug Fix]: Improved conditional logic for creating evaluator
  agenta-web/src/components/pages/evaluations/evaluators/AdvancedSettings.tsx
  agenta-web/src/components/pages/evaluations/evaluators/NewEvaluatorModal.tsx
Labels: bug, Frontend, size:M, lgtm

#1733 Hotfix evaluation
  agenta-backend/agenta_backend/services/evaluators_service.py
Labels: bug, Backend, size:XS

#1744 Hotfix to show the correct answers even for evalutors that are not correctly migrated
  agenta-backend/agenta_backend/tasks/evaluations.py
Labels: bug, Backend, size:XS

#1746 Evaluation fix
  agenta-backend/agenta_backend/tasks/evaluations.py
Labels: bug, Backend, size:XS

#1748 merge main
  agenta-backend/agenta_backend/tasks/evaluations.py
Labels: size:XS

#1735 fix(migration): add missing correct answer for evaluators
  agenta-backend/agenta_backend/migrations/v0_16_0_to_v0_16_0_1/20240602150517_evaluators.py
  agenta-backend/agenta_backend/services/evaluators_service.py
  agenta-backend/agenta_backend/tasks/evaluations.py
Labels: bug, Backend, size:L, lgtm

#1736 Candidate fix to #1705 (pydantic v2)
  agenta-web/src/lib/helpers/openapi_parser.ts
Labels: bug, typescript, size:S, lgtm

#1750 Bugfix/code-evaluators
  agenta-backend/agenta_backend/migrations/v0_16_0_1_to_v0_16_0_2/20240603145957_code_evaluators.py
  agenta-backend/agenta_backend/resources/evaluators/evaluators.py
  agenta-backend/agenta_backend/services/aggregation_service.py
  agenta-backend/agenta_backend/services/evaluators_service.py
  agenta-backend/agenta_backend/services/security/sandbox.py
Labels: bug, Backend, size:L, lgtm

#1752 chore(tools): added better commits for conventional commits
  .better-commits.json
Labels: size:L, lgtm

#1743 fix: fixed testset columns naming conventions
  agenta-web/src/components/TestSetTable/TestsetTable.tsx
Labels: bug, Frontend, size:S, lgtm

#1757 chore: Improved scope for better commit
  .better-commits.json
Labels: size:S

#1705 [Migration]: upgrade pydantic to v2 with sdk compatibility
  .github/workflows/run-frontend-tests.yml
  agenta-cli/agenta/docker/docker-assets/Dockerfile.cloud.template
  agenta-cli/agenta/sdk/decorators/llm_entrypoint.py
  agenta-cli/agenta/sdk/types.py
  agenta-cli/poetry.lock
  agenta-cli/pyproject.toml
  agenta-web/src/lib/helpers/openapi_parser.ts
  docker-compose.test.yml
Labels: enhancement, SDK, size:L, lgtm

#1756 fix(app): #1747 Fix showing params in the playground
  agenta-web/src/components/Playground/Views/ParametersCards.tsx
Labels: bug, Frontend, size:S, lgtm

#1766 fix (sdk): set default values to FuncResponse sdk type
  agenta-cli/agenta/sdk/decorators/llm_entrypoint.py
Labels: bug, SDK, size:XS, lgtm

#1763 [Feature]: Export results in the Evaluation Scenarios view
  agenta-web/src/components/pages/evaluations/cellRenderers/cellRenderers.tsx
  agenta-web/src/components/pages/evaluations/evaluationCompare/EvaluationCompare.tsx
  agenta-web/src/components/pages/evaluations/evaluationResults/EvaluationResults.tsx
  agenta-web/src/components/pages/evaluations/evaluationScenarios/EvaluationScenarios.tsx
Labels: Frontend, feature, typescript, size:L, lgtm

#1603 [Enhancement]: add integration with litellm for observability
  agenta-cli/agenta/__init__.py
  agenta-cli/agenta/sdk/__init__.py
  agenta-cli/agenta/sdk/decorators/tracing.py
  agenta-cli/agenta/sdk/tracing/__init__.py
  agenta-cli/agenta/sdk/tracing/callbacks.py
  agenta-cli/agenta/sdk/tracing/llm_tracing.py
  agenta-cli/poetry.lock
  examples/app_with_observability/litellm_integration.py
Labels: enhancement, CLI, SDK, size:L, lgtm, observability

#1771 [Hotfix]: resolve ChatCompletionMessage object is not subscriptable
  agenta-backend/agenta_backend/services/evaluators_service.py
  docker-compose.test.yml
Labels: bug, Backend, size:XS, lgtm

#1775 [Docs]: Update the team management page in the docs
  docs/images/misc/team_management_dark.png
  docs/images/misc/team_management_light.png
  docs/images/misc/workspace_tab_dark.png
  docs/images/misc/workspace_tab_light.png
  docs/misc/team_management.mdx
Labels: documentation, size:S, lgtm

#1740 Propagate cost and tokens
  agenta-cli/agenta/client/backend/types/llm_tokens.py
  agenta-cli/agenta/sdk/tracing/llm_tracing.py
Labels: CLI, SDK, size:M, lgtm

#1784 Enhancement: Upgrade to Next 14
  agenta-web/next.config.js
  agenta-web/package-lock.json
  agenta-web/package.json
Labels: enhancement, Frontend, size:S, lgtm

#1623 Refactor API Endpoints into Services Folder
  agenta-web/src/components/AppSelector/AppCard.tsx
  agenta-web/src/components/AppSelector/AppSelector.tsx
  agenta-web/src/components/EvaluationTable/ABTestingEvaluationTable.tsx
  agenta-web/src/components/EvaluationTable/SingleModelEvaluationTable.tsx
  agenta-web/src/components/Evaluations/AutomaticEvaluationResult.tsx
  agenta-web/src/components/Evaluations/HumanEvaluationResult.tsx
  agenta-web/src/components/HumanEvaluationModal/HumanEvaluationModal.tsx
  agenta-web/src/components/Layout/Layout.tsx
  agenta-web/src/components/Playground/AddToTestSetDrawer/AddToTestSetDrawer.tsx
  agenta-web/src/components/Playground/LoadTestsModal.tsx
  agenta-web/src/components/Playground/Playground.tsx
  agenta-web/src/components/Playground/ViewNavigation.tsx
  agenta-web/src/components/Playground/Views/ParametersView.tsx
  agenta-web/src/components/Playground/Views/PublishVariantModal.tsx
  agenta-web/src/components/Playground/Views/TestView.tsx
  agenta-web/src/components/SaveTestsetModal/SaveTestsetModal.tsx
  agenta-web/src/components/TestSetTable/TestsetTable.tsx
  agenta-web/src/components/pages/evaluations/evaluationCompare/EvaluationCompare.tsx
  agenta-web/src/components/pages/evaluations/evaluationResults/EvaluationResults.tsx
  agenta-web/src/components/pages/evaluations/evaluationResults/NewEvaluationModal.tsx
  agenta-web/src/components/pages/evaluations/evaluationScenarios/EvaluationScenarios.tsx
  agenta-web/src/components/pages/evaluations/evaluators/EvaluatorCard.tsx
  agenta-web/src/components/pages/evaluations/evaluators/Evaluators.tsx
  agenta-web/src/components/pages/evaluations/evaluators/NewEvaluatorModal.tsx
  agenta-web/src/contexts/app.context.tsx
  agenta-web/src/contexts/profile.context.tsx
  agenta-web/src/lib/helpers/evaluate.ts
  agenta-web/src/lib/helpers/variantHelper.ts
  agenta-web/src/lib/hooks/useVariant.ts
  agenta-web/src/lib/services/api.ts
  agenta-web/src/lib/services/evaluations.ts
  agenta-web/src/pages/apps/[app_id]/annotations/human_a_b_testing/[evaluation_id]/index.tsx
  agenta-web/src/pages/apps/[app_id]/annotations/single_model_test/[evaluation_id]/index.tsx
  agenta-web/src/pages/apps/[app_id]/endpoints/index.tsx
  agenta-web/src/pages/apps/[app_id]/evaluations/new-evaluator.tsx
  agenta-web/src/pages/apps/[app_id]/evaluations/results.tsx
  agenta-web/src/pages/apps/[app_id]/testsets/index.tsx
  agenta-web/src/services/api.ts
  agenta-web/src/services/app-selector/api/index.ts
  agenta-web/src/services/deployment/api/index.ts
  agenta-web/src/services/evaluations/api/index.ts
  agenta-web/src/services/human-evaluations/api/index.ts
  agenta-web/src/services/playground/api/index.ts
  agenta-web/src/services/testsets/api/index.ts
Labels: Frontend, refactoring, typescript, size:XL, lgtm

#1787 fix(backend): candidate hotfix for failing evals
  agenta-backend/agenta_backend/services/llm_apps_service.py
Labels: bug, Backend, size:XS

#1788 [Enhancement]: Refactor ForeignKey with CASCADE behavior
  agenta-backend/agenta_backend/models/db_models.py
Labels: enhancement, Backend, size:L, lgtm, db

#1795 [Bug]: Redirect Issue When Deleting Evaluation in Evaluation Results View
  agenta-web/src/components/pages/evaluations/evaluationScenarios/EvaluationScenarios.tsx
Labels: bug, Frontend, size:XS, lgtm

#1797 Fix: error when pulling environment configuration
  agenta-backend/agenta_backend/services/app_manager.py
  agenta-cli/agenta/sdk/agenta_init.py
  agenta-cli/pyproject.toml
Labels: bug, Backend, SDK, size:XS, lgtm

#1781 feat(db-postgres): code migration from Beanie to SQLAlchemy
  agenta-backend/agenta_backend/main.py
  agenta-backend/agenta_backend/models/api/api_models.py
  agenta-backend/agenta_backend/models/api/evaluation_model.py
  agenta-backend/agenta_backend/models/api/testset_model.py
  agenta-backend/agenta_backend/models/api/user_models.py
  agenta-backend/agenta_backend/models/converters.py
  agenta-backend/agenta_backend/models/db_engine.py
  agenta-backend/agenta_backend/models/db_models.py
  agenta-backend/agenta_backend/models/shared_models.py
  agenta-backend/agenta_backend/routers/app_router.py
  agenta-backend/agenta_backend/routers/bases_router.py
  agenta-backend/agenta_backend/routers/configs_router.py
  agenta-backend/agenta_backend/routers/container_router.py
  agenta-backend/agenta_backend/routers/evaluation_router.py
  agenta-backend/agenta_backend/routers/evaluators_router.py
  agenta-backend/agenta_backend/routers/human_evaluation_router.py
  agenta-backend/agenta_backend/routers/testset_router.py
  agenta-backend/agenta_backend/routers/user_profile.py
  agenta-backend/agenta_backend/routers/variants_router.py
  agenta-backend/agenta_backend/services/aggregation_service.py
  agenta-backend/agenta_backend/services/app_manager.py
  agenta-backend/agenta_backend/services/db_manager.py
  agenta-backend/agenta_backend/services/deployment_manager.py
  agenta-backend/agenta_backend/services/evaluation_service.py
  agenta-backend/agenta_backend/services/evaluator_manager.py
  agenta-backend/agenta_backend/services/evaluators_service.py
  agenta-backend/agenta_backend/services/llm_apps_service.py
  agenta-backend/agenta_backend/services/results_service.py
  agenta-backend/agenta_backend/tasks/evaluations.py
  agenta-backend/agenta_backend/tests/conftest.py
  agenta-backend/agenta_backend/tests/variants_main_router/conftest.py
  agenta-backend/poetry.lock
  agenta-backend/pyproject.toml
  docker-compose.test.yml
  docker-compose.yml
Labels: size:XXL, db

#1791 Fix: cleared 'Create a New Variant' modal input data
  agenta-web/src/components/Playground/NewVariantModal.tsx
Labels: UX, typescript, size:XS, lgtm

#1808 Dependabot prs
  agenta-cli/poetry.lock
  agenta-cli/pyproject.toml
Labels: dependencies, size:XS

#1796 [Fix]: Human Evaluation inputs overflowing when values are long
  agenta-web/src/components/EvaluationTable/ABTestingEvaluationTable.tsx
  agenta-web/src/components/EvaluationTable/SingleModelEvaluationTable.tsx
  agenta-web/src/components/Playground/ParamsForm/ParamsForm.tsx
Labels: bug, Frontend, size:M, lgtm

#1777 Refactor: improved the testset new api page import path
  agenta-web/src/pages/apps/[app_id]/testsets/new/api/index.tsx
Labels: Frontend, refactoring, size:S, lgtm

#1818 fix(backend): 1817 fix access to variant revision
  agenta-backend/agenta_backend/models/converters.py
Labels: bug, Backend, size:XS, lgtm

#1814 [Bug] Not all rows in evaluation comparison cannot be expanded
  agenta-web/src/components/pages/evaluations/evaluationCompare/EvaluationCompare.tsx
  agenta-web/src/services/evaluations/api/index.ts
Labels: bug, Frontend, size:XS, lgtm

#1813 [Bug]: UI Creates Duplicate Entries When Saving New Test Set Multiple Times
  agenta-web/src/components/TestSetTable/TestsetTable.tsx
  agenta-web/src/pages/apps/[app_id]/testsets/[testset_id]/index.tsx
Labels: bug, UI, size:S, lgtm

#1820 fix(backend): Score Calculation for Human Single Modal differs in view
  agenta-backend/agenta_backend/services/results_service.py
Labels: bug, Backend, size:XS, lgtm

#1822 docs(tool): AGE-367 added new cookbook
  cookbook/creating_evaluators_with_sdk.ipynb
Labels: documentation, size:L

#1823 docs(tool): AGE-367 add doc for using sdk
  docs/guides/evaluation_from_sdk.mdx
  docs/mint.json
Labels: size:L

#1828 Merge cloud migration into postgres data migration
  agenta-backend/agenta_backend/models/api/api_models.py
  agenta-backend/agenta_backend/models/converters.py
  agenta-backend/agenta_backend/models/db_engine.py
  agenta-backend/agenta_backend/models/db_models.py
  agenta-backend/agenta_backend/routers/app_router.py
  agenta-backend/agenta_backend/routers/configs_router.py
  agenta-backend/agenta_backend/routers/evaluation_router.py
  agenta-backend/agenta_backend/routers/evaluators_router.py
  agenta-backend/agenta_backend/routers/human_evaluation_router.py
  agenta-backend/agenta_backend/routers/testset_router.py
  agenta-backend/agenta_backend/routers/variants_router.py
  agenta-backend/agenta_backend/services/app_manager.py
  agenta-backend/agenta_backend/services/db_manager.py
  agenta-backend/agenta_backend/services/deployment_manager.py
  agenta-backend/agenta_backend/services/evaluator_manager.py
  agenta-backend/agenta_backend/services/user_service.py
  agenta-backend/agenta_backend/tasks/evaluations.py
Labels: size:XL
