Repository Agenta-AI/agenta, pull requests merged in 2024-11, with the labels that each got.

#2167 fix(frontend): moved all the query states in the context-api
  agenta-web/src/contexts/observability.context.tsx
  agenta-web/src/pages/apps/[app_id]/observability/index.tsx
  agenta-web/src/services/observability/core/index.ts
Labels: Frontend, size:L, lgtm

#2168 fix(frontend): added human friendly filter column names
  agenta-web/src/pages/apps/[app_id]/observability/index.tsx
Labels: Frontend, size:M, lgtm

#2169 (frontend)[Age 1137]: Update design for JSON/YAML switch different
  agenta-web/src/components/pages/observability/components/AccordionTreePanel.tsx
Labels: Frontend, size:S, lgtm

#2163 (frontend)[Age 1181]: Traces with on single main span are not correctly rendered
  agenta-web/src/components/pages/observability/drawer/TraceTree.tsx
Labels: Frontend, size:XS, lgtm

#2157 (frontend)[Age 1178]Wrong latency shown in table and drawer
  agenta-web/src/components/pages/observability/drawer/TraceContent.tsx
  agenta-web/src/components/pages/observability/drawer/TraceTree.tsx
  agenta-web/src/lib/helpers/formatters.ts
  agenta-web/src/pages/apps/[app_id]/observability/index.tsx
Labels: bug, Frontend, size:S, lgtm

#2171 Updated video quick start tutorial
  docs/docs/getting-started/02-quick-start.mdx
Labels: documentation, size:XS, lgtm

#2161 fix(frontend): rearranged observability table columns
  agenta-web/src/pages/apps/[app_id]/observability/index.tsx
Labels: Frontend, UX, size:M

#2156 feat(frontend): add global observability page
  agenta-web/src/components/Filters/Filters.tsx
  agenta-web/src/components/Sidebar/config.tsx
  agenta-web/src/components/pages/observability/ObservabilityDashboard.tsx
  agenta-web/src/contexts/observability.context.tsx
  agenta-web/src/lib/Types.ts
  agenta-web/src/pages/apps/[app_id]/traces/index.tsx
  agenta-web/src/pages/observability/index.tsx
Labels: Frontend, feature, size:L

#2173 fix(frontend): observability filter column names style
  agenta-web/src/components/Filters/Filters.tsx
  agenta-web/src/components/pages/observability/ObservabilityDashboard.tsx
Labels: Frontend, size:S, lgtm

#2175 fix(frontend): replaced data property with content for search filter
  agenta-web/src/components/pages/observability/ObservabilityDashboard.tsx
Labels: bug, Frontend, size:S, lgtm

#2177 Adjust dependabot config file
  .github/dependabot.yml
Labels: dependencies, size:S, lgtm

#2147 [Dependency]: Access control in API Keys
  agenta-backend/agenta_backend/routers/app_router.py
  agenta-backend/agenta_backend/services/app_manager.py
Labels: size:XS, lgtm

#2194 limit dependabot to only security udates
  .github/dependabot.yml
Labels: dependencies, size:S, lgtm

#2174 LLM as a judge improvements
  agenta-backend/agenta_backend/resources/evaluators/evaluators.py
  agenta-backend/agenta_backend/services/evaluators_service.py
  agenta-backend/poetry.lock
  agenta-backend/pyproject.toml
  agenta-web/package-lock.json
  agenta-web/package.json
  agenta-web/src/components/pages/evaluations/autoEvaluation/EvaluatorsModal/ConfigureEvaluator/AdvancedSettings.tsx
  agenta-web/src/components/pages/evaluations/autoEvaluation/EvaluatorsModal/ConfigureEvaluator/DynamicFormField.tsx
  agenta-web/src/components/pages/evaluations/autoEvaluation/EvaluatorsModal/ConfigureEvaluator/Messages.tsx
  agenta-web/src/lib/Types.ts
Labels: Frontend, Backend, typescript, improvement, size:L, lgtm

#2219 remove dependabot.yml
  .github/dependabot.yml
Labels: size:M, lgtm

#2176 fix(frontend): observability filter apply and clear conditions
  agenta-web/src/components/Filters/Filters.tsx
Labels: bug, Frontend, size:S, lgtm

#2228 fix path-to-regexp
  docs/package-lock.json
  docs/package.json
Labels: dependencies, size:XS, lgtm

#2229 Fix starlette vulnerability
  agenta-backend/poetry.lock
  agenta-backend/pyproject.toml
Labels: dependencies, size:XS, lgtm

#2233 fix(frontend): observability filter column names according to table columns
  agenta-web/src/components/pages/observability/ObservabilityDashboard.tsx
Labels: bug, Frontend, size:XS, lgtm

#2234 fix(frontend): broken observability windowing logic and format
  agenta-web/src/components/Filters/Sort.tsx
  agenta-web/src/contexts/observability.context.tsx
Labels: bug, Frontend, size:M, lgtm

#2235 fix(frontend): trace drawer time, cost font style
  agenta-web/src/components/pages/observability/drawer/TraceContent.tsx
  agenta-web/src/components/pages/observability/drawer/TraceTree.tsx
Labels: Frontend, size:M, lgtm

#2238 fix(frontend): delete evaluation redirection url
  agenta-web/src/components/pages/evaluations/evaluationScenarios/EvaluationScenarios.tsx
Labels: bug, Frontend, size:XS, lgtm

#2237 (frontend)[Age 1270]: Raw data missing data in overview
  agenta-web/src/components/pages/observability/drawer/TraceContent.tsx
Labels: bug, Backend, size:S, lgtm

#2236 (frontend)[Age 1243]: Variant details fails to open after updating a variant
  agenta-web/src/components/pages/overview/variants/VariantDrawer.tsx
Labels: bug, Frontend, size:XS, lgtm

#2241 fix(frontend): removed autocomplete from llm as a judge
  agenta-web/src/components/pages/evaluations/autoEvaluation/EvaluatorsModal/ConfigureEvaluator/Messages.tsx
Labels: UI, size:XS, lgtm

#2242 (frontend)[AGE-1262]: Values that are set to 0 are lost when exiting and re-entering
  agenta-web/src/components/Evaluations/EvaluationCardView/EvaluationVotePanel.tsx
Labels: bug, Frontend, size:XS, lgtm

#2243 (frontend)[AGE-1258]: Highlighting of variables in LLM-as-a-Judge is functional but coloring is buggy
  agenta-web/src/components/pages/evaluations/autoEvaluation/EvaluatorsModal/ConfigureEvaluator/Messages.tsx
Labels: bug, size:XS, lgtm

#2240 fix(backend): predefined app environment order
  agenta-backend/agenta_backend/routers/app_router.py
Labels: bug, Backend, size:S, lgtm

#2230 fix(frontend): avatar profiles color
  agenta-web/src/components/Avatar/Avatar.tsx
  agenta-web/src/components/HumanEvaluations/AbTestingEvaluation.tsx
  agenta-web/src/components/Sidebar/Sidebar.tsx
  agenta-web/src/components/pages/evaluations/evaluationCompare/EvaluationCompare.tsx
  agenta-web/src/lib/helpers/colors.ts
Labels: Frontend, antd, size:L, lgtm

#2245 fix(frontend): observability export data format
  agenta-web/src/components/pages/observability/ObservabilityDashboard.tsx
Labels: bug, Frontend, size:S, lgtm

#2247 [Enhancement]: Improve Prompt Management Documentation
  agenta-cli/agenta/sdk/managers/config.py
  agenta-cli/agenta/tests/prompt_sdk/test_config_manager.py
  docs/docs/prompt-management/02-quick-start.mdx
  docs/docs/prompt-management/03-prompt-management-sdk.mdx
  docs/docs/tutorials/sdk/manage-prompts-with-SDK.mdx
Labels: documentation, enhancement, size:L, lgtm

#2220 docs(app): AGE-1228 changelog 0.27.0
  docs/blog/main.mdx
  docs/docs/evaluation/evaluators/04-llm-as-a-judge.mdx
  docs/static/images/evaluation/llm-as-a-judge.gif
  docs/static/images/evaluation/llm-as-a-judge.png
Labels: documentation, size:L, lgtm

#2256 Fix/sdk kwargs app
  agenta-cli/agenta/sdk/decorators/routing.py
Labels: SDK, size:XS, lgtm

#2255 [Fix] (SDK) api key not fetched from self.api_key
  agenta-cli/agenta/sdk/agenta_init.py
Labels: bug, SDK, size:S, lgtm

#2257 v0.27.2
  agenta-backend/pyproject.toml
  agenta-cli/pyproject.toml
  agenta-web/package-lock.json
  agenta-web/package.json
Labels: dependencies, size:XS, lgtm

#2259 docs(app): added blog link to docs
  docs/docusaurus.config.ts
Labels: documentation, size:XS, lgtm

#2263 Fix bump workflow
  .github/workflows/bump-versions.yml
Labels: ci/cd, size:M, lgtm

#2166 [Feature] Application Security
  .github/actions/check-app-accessibility/action.yml
  .github/workflows/cli-commands-tests.yml
  agenta-backend/agenta_backend/main.py
  agenta-backend/agenta_backend/routers/evaluation_router.py
  agenta-backend/agenta_backend/routers/permissions_router.py
  agenta-backend/agenta_backend/services/llm_apps_service.py
  agenta-backend/agenta_backend/tasks/evaluations.py
  agenta-backend/agenta_backend/tests/unit/test_llm_apps_service.py
  agenta-cli/agenta/sdk/decorators/routing.py
  agenta-cli/agenta/sdk/middleware/__init__.py
  agenta-cli/agenta/sdk/middleware/auth.py
  agenta-cli/agenta/sdk/middleware/cache.py
  agenta-cli/agenta/sdk/tracing/exporters.py
  agenta-cli/agenta/sdk/tracing/processors.py
  agenta-cli/pyproject.toml
Labels: Backend, CLI, feature, SDK, size:L, lgtm

#2271 (frontend)[Age-1286]: Update web UI to use BaseResponse version 3.0 in the Playground
  agenta-web/src/components/Playground/Views/TestView.tsx
  agenta-web/src/components/pages/observability/drawer/TraceContent.tsx
  agenta-web/src/components/pages/observability/drawer/TraceHeader.tsx
  agenta-web/src/components/pages/observability/drawer/TraceTree.tsx
  agenta-web/src/lib/Types.ts
  agenta-web/src/lib/helpers/observability_helpers.ts
Labels: UI, size:L

#2273 Added Cookbook observability Langchain
  cookbook/observability_langchain.ipynb
  docs/docs/tutorials/cookbooks/observability_langchain.mdx
  docs/sidebars.ts
  docs/static/images/cookbooks/langchain-tracing.png
Labels: documentation, size:L

#2253 [Enhancement] Extend Backend to Support SDK base response version 3.0 for RAG Evaluators
  agenta-backend/agenta_backend/services/evaluators_service.py
  agenta-backend/agenta_backend/services/llm_apps_service.py
  agenta-backend/agenta_backend/tests/unit/test_evaluators.py
  agenta-backend/agenta_backend/tests/unit/test_traces.py
  agenta-backend/agenta_backend/utils/traces.py
  agenta-cli/agenta/sdk/decorators/routing.py
  agenta-cli/agenta/sdk/types.py
  agenta-cli/pyproject.toml
Labels: enhancement, refactoring, size:XL

#2251 [Enhancement] Update SDK to return BaseResponse version 3.0 and new trace tree format
  agenta-backend/agenta_backend/services/evaluators_service.py
  agenta-backend/agenta_backend/services/llm_apps_service.py
  agenta-backend/agenta_backend/tests/unit/test_evaluators.py
  agenta-backend/agenta_backend/tests/unit/test_traces.py
  agenta-backend/agenta_backend/utils/traces.py
  agenta-cli/agenta/client/backend/__init__.py
  agenta-cli/agenta/client/backend/client.py
  agenta-cli/agenta/client/backend/core/http_client.py
  agenta-cli/agenta/client/backend/observability/client.py
  agenta-cli/agenta/client/backend/observability_v_1/__init__.py
  agenta-cli/agenta/client/backend/observability_v_1/client.py
  agenta-cli/agenta/client/backend/observability_v_1/types/__init__.py
  agenta-cli/agenta/client/backend/observability_v_1/types/format.py
  agenta-cli/agenta/client/backend/observability_v_1/types/query_traces_response.py
  agenta-cli/agenta/client/backend/types/__init__.py
  agenta-cli/agenta/client/backend/types/agenta_node_dto.py
  agenta-cli/agenta/client/backend/types/agenta_node_dto_nodes_value.py
  agenta-cli/agenta/client/backend/types/agenta_nodes_response.py
  agenta-cli/agenta/client/backend/types/agenta_root_dto.py
  agenta-cli/agenta/client/backend/types/agenta_roots_response.py
  agenta-cli/agenta/client/backend/types/agenta_tree_dto.py
  agenta-cli/agenta/client/backend/types/agenta_trees_response.py
  agenta-cli/agenta/client/backend/types/collect_status_response.py
  agenta-cli/agenta/client/backend/types/exception_dto.py
  agenta-cli/agenta/client/backend/types/link_dto.py
  agenta-cli/agenta/client/backend/types/node_dto.py
  agenta-cli/agenta/client/backend/types/node_type.py
  agenta-cli/agenta/client/backend/types/o_tel_context_dto.py
  agenta-cli/agenta/client/backend/types/o_tel_event_dto.py
  agenta-cli/agenta/client/backend/types/o_tel_extra_dto.py
  agenta-cli/agenta/client/backend/types/o_tel_link_dto.py
  agenta-cli/agenta/client/backend/types/o_tel_span_dto.py
  agenta-cli/agenta/client/backend/types/o_tel_span_kind.py
  agenta-cli/agenta/client/backend/types/o_tel_spans_response.py
  agenta-cli/agenta/client/backend/types/o_tel_status_code.py
  agenta-cli/agenta/client/backend/types/parent_dto.py
  agenta-cli/agenta/client/backend/types/root_dto.py
  agenta-cli/agenta/client/backend/types/span_dto.py
  agenta-cli/agenta/client/backend/types/span_dto_nodes_value.py
  agenta-cli/agenta/client/backend/types/status_code.py
  agenta-cli/agenta/client/backend/types/status_dto.py
  agenta-cli/agenta/client/backend/types/time_dto.py
  agenta-cli/agenta/client/backend/types/tree_dto.py
  agenta-cli/agenta/client/backend/types/tree_type.py
  agenta-cli/agenta/client/backend/variants/client.py
  agenta-cli/agenta/sdk/__init__.py
  agenta-cli/agenta/sdk/decorators/routing.py
  agenta-cli/agenta/sdk/tracing/inline.py
  agenta-cli/agenta/sdk/types.py
  agenta-cli/pyproject.toml
  agenta-web/src/components/Playground/Views/TestView.tsx
  agenta-web/src/components/pages/observability/drawer/TraceContent.tsx
  agenta-web/src/components/pages/observability/drawer/TraceHeader.tsx
  agenta-web/src/components/pages/observability/drawer/TraceTree.tsx
  agenta-web/src/lib/Types.ts
  agenta-web/src/lib/helpers/observability_helpers.ts
  agenta-web/src/lib/helpers/playgroundResp.ts
  agenta-web/src/services/observability/types/index.ts
Labels: enhancement, SDK, size:XXL

#2204 [Feature] Observability Analytics (MongoDB replacement)
  agenta-backend/agenta_backend/apis/fastapi/observability/models.py
  agenta-backend/agenta_backend/apis/fastapi/observability/router.py
  agenta-backend/agenta_backend/apis/fastapi/observability/utils.py
  agenta-backend/agenta_backend/core/observability/dtos.py
  agenta-backend/agenta_backend/core/observability/interfaces.py
  agenta-backend/agenta_backend/core/observability/service.py
  agenta-backend/agenta_backend/dbs/postgres/observability/dao.py
  agenta-backend/agenta_backend/dbs/postgres/observability/mappings.py
  agenta-cli/tests/observability_sdk/integrations/litellm/01_sanity_check.py
Labels: Backend, feature, size:XL, lgtm

#2278 Update pyproject.toml
  agenta-cli/pyproject.toml
Labels: size:XS, lgtm

#2265 fix(frontend): search input icon height issue
  agenta-web/src/styles/globals.css
Labels: bug, size:XS, lgtm

#2269 [Feautre] Add custom redact functionality to SDK
  agenta-cli/agenta/__init__.py
  agenta-cli/agenta/sdk/__init__.py
  agenta-cli/agenta/sdk/agenta_init.py
  agenta-cli/agenta/sdk/decorators/tracing.py
  agenta-cli/agenta/sdk/tracing/tracing.py
  agenta-cli/tests/redact/01_ignore_all.py
  agenta-cli/tests/redact/02_ignore_all_inputs.py
  agenta-cli/tests/redact/03_ignore_all_outputs.py
  agenta-cli/tests/redact/04_ignore_some.py
  agenta-cli/tests/redact/05_redact_instrument.py
  agenta-cli/tests/redact/06_redact_init.py
  agenta-cli/tests/redact/07_redact_combined.py
  agenta-cli/tests/redact/08_redect_or_error_false.py
  agenta-cli/tests/redact/08_redect_or_error_true.py
  agenta-cli/tests/redact/requirements.txt
  docs/docs/observability/03-observability-sdk.mdx
Labels: feature, SDK, tests, size:L, lgtm

#2267 [Chore] clean up agenta-cli dependencies
  agenta-cli/agenta/tests/management_sdk/v1.py
  agenta-cli/agenta/tests/management_sdk/v2.py
  agenta-cli/agenta/tests/management_sdk/v4_prompt.py
  agenta-cli/poetry.lock
  agenta-cli/pyproject.toml
Labels: CLI, dependencies, size:XS, lgtm

#2254 Litellm patch
  agenta-cli/agenta/sdk/litellm/litellm.py
Labels: SDK, size:M, lgtm

#2246 (frontend)[AGE-1011]: Solve size modal issue
  agenta-web/src/components/pages/evaluations/autoEvaluation/EvaluatorsModal/ConfigureEvaluator/index.tsx
  agenta-web/src/components/pages/evaluations/autoEvaluation/EvaluatorsModal/EvaluatorsModal.tsx
Labels: Frontend, size:M, lgtm

#2281 AGE-1359 Minor fix to fetch prompt docs
  docs/docs/prompt-management/integration/02-fetch-prompts.mdx
Labels: documentation, size:M, lgtm

#2285 [Fix] AGE-1360
  agenta-backend/agenta_backend/core/observability/utils.py
Labels: size:XS, lgtm

#2287 Revert pyproject.toml
  agenta-cli/pyproject.toml
Labels: size:XS

#2283 [Enhancement]: CORS + App Security hotfix
  agenta-backend/agenta_backend/routers/permissions_router.py
  agenta-backend/agenta_backend/services/llm_apps_service.py
  agenta-backend/agenta_backend/tasks/evaluations.py
  agenta-cli/agenta/sdk/decorators/routing.py
  agenta-cli/agenta/sdk/middleware/auth.py
  agenta-cli/agenta/sdk/types.py
  agenta-web/src/services/api.ts
Labels: bug, Backend, size:L, lgtm

#2292 fix(frontend): prompt fetching code
  agenta-web/src/code_snippets/endpoints/fetch_config/curl.ts
  agenta-web/src/code_snippets/endpoints/fetch_config/python.ts
  agenta-web/src/code_snippets/endpoints/fetch_config/typescript.ts
  agenta-web/src/components/pages/overview/deployments/DeploymentDrawer.tsx
Labels: bug, Frontend, size:L, lgtm

#2290 (frontend)[AGE-1342]: Auto-refresh observability tables
  agenta-web/src/components/pages/observability/ObservabilityDashboard.tsx
Labels: enhancement, Frontend, size:S, lgtm

#2272 [Feature]: Project-checkpoint-4
  agenta-backend/agenta_backend/main.py
  agenta-backend/agenta_backend/routers/projects_router.py
  agenta-backend/agenta_backend/services/db_manager.py
  agenta-cli/pyproject.toml
  agenta-web/cypress/e2e/ab-testing-evaluation.cy.ts
  agenta-web/cypress/e2e/eval.comparison.cy.ts
  agenta-web/cypress/e2e/single-model-test-evaluation.cy.ts
  agenta-web/cypress/support/commands/evaluations.ts
  agenta-web/src/components/pages/evaluations/evaluationCompare/EvaluationCompare.tsx
  agenta-web/src/components/pages/evaluations/evaluationScenarios/EvaluationScenarios.tsx
  agenta-web/src/components/pages/overview/deployments/DeploymentDrawer.tsx
  agenta-web/src/contexts/app.context.tsx
  agenta-web/src/contexts/project.context.tsx
  agenta-web/src/pages/_app.tsx
  agenta-web/src/pages/apps/[app_id]/endpoints/index.tsx
  agenta-web/src/services/api.ts
  agenta-web/src/services/app-selector/api/index.ts
  agenta-web/src/services/deployment/api/index.ts
  agenta-web/src/services/evaluations/api/index.ts
  agenta-web/src/services/human-evaluations/api/index.ts
  agenta-web/src/services/observability/core/index.ts
  agenta-web/src/services/playground/api/index.ts
  agenta-web/src/services/project/index.ts
  agenta-web/src/services/testsets/api/index.ts
Labels: Frontend, Backend, feature, typescript, size:XL, lgtm

#1994 [Enhancement]: Add 'app_type' column for AppDB model with updated API responses
  agenta-backend/agenta_backend/migrations/postgres/data_migrations/projects.py
  agenta-backend/agenta_backend/migrations/postgres/versions/0f086ebc2f82_added_the_app_type_column_to_the_app_db_.py
  agenta-backend/agenta_backend/models/api/api_models.py
  agenta-backend/agenta_backend/models/converters.py
  agenta-backend/agenta_backend/models/db_models.py
  agenta-backend/agenta_backend/models/deprecated_models.py
  agenta-backend/agenta_backend/models/shared_models.py
  agenta-backend/agenta_backend/routers/app_router.py
  agenta-backend/agenta_backend/services/db_manager.py
  agenta-cli/pyproject.toml
  agenta-web/src/components/AppSelector/AppCard.tsx
  agenta-web/src/lib/Types.ts
Labels: enhancement, Backend, CLI, size:L, lgtm

#2295 fix(frontend): observability input column data in export results
  agenta-web/src/components/pages/observability/ObservabilityDashboard.tsx
Labels: bug, Frontend, size:XS, lgtm

#2289 [Fix] litellm streaming warnings
  agenta-cli/agenta/sdk/litellm/litellm.py
  agenta-cli/tests/observability_sdk/integrations/litellm/03_agenta_implementationa_streaming.py
Labels: bug, SDK, tests, size:L, lgtm

#2266 [feat] global testsets
  agenta-backend/agenta_backend/routers/evaluation_router.py
  agenta-backend/agenta_backend/routers/testset_router.py
  agenta-backend/agenta_backend/services/db_manager.py
  agenta-backend/agenta_backend/tests/variants_main_router/test_variant_testset_router.py
  agenta-cli/agenta/client/backend/evaluations/client.py
  agenta-cli/agenta/client/backend/testsets/client.py
  agenta-web/cypress/e2e/eval.evaluations.cy.ts
  agenta-web/cypress/e2e/single-model-test-evaluation.cy.ts
  agenta-web/cypress/e2e/testset.cy.ts
  agenta-web/cypress/support/commands/evaluations.ts
  agenta-web/src/code_snippets/testsets/create_with_upload/curl.ts
  agenta-web/src/code_snippets/testsets/create_with_upload/python.ts
  agenta-web/src/code_snippets/testsets/create_with_upload/typescript.ts
  agenta-web/src/components/HumanEvaluationModal/HumanEvaluationModal.tsx
  agenta-web/src/components/HumanEvaluations/AbTestingEvaluation.tsx
  agenta-web/src/components/HumanEvaluations/SingleModelEvaluation.tsx
  agenta-web/src/components/Playground/AddToTestSetDrawer/AddToTestSetDrawer.tsx
  agenta-web/src/components/Playground/LoadTestsModal.tsx
  agenta-web/src/components/SaveTestsetModal/SaveTestsetModal.tsx
  agenta-web/src/components/Sidebar/config.tsx
  agenta-web/src/components/TestSetTable/TestsetTable.tsx
  agenta-web/src/components/pages/evaluations/NewEvaluation/NewEvaluationModal.tsx
  agenta-web/src/components/pages/evaluations/autoEvaluation/AutoEvaluation.tsx
  agenta-web/src/components/pages/evaluations/autoEvaluation/EvaluatorsModal/EvaluatorsModal.tsx
  agenta-web/src/components/pages/evaluations/evaluationCompare/EvaluationCompare.tsx
  agenta-web/src/components/pages/evaluations/evaluationScenarios/EvaluationScenarios.tsx
  agenta-web/src/components/pages/overview/automaticEvaluation/AutomaticEvalOverview.tsx
  agenta-web/src/components/pages/testset/modals/CreateTestsetFromApi.tsx
  agenta-web/src/components/pages/testset/modals/CreateTestsetFromScratch.tsx
  agenta-web/src/components/pages/testset/modals/UploadTestset.tsx
  agenta-web/src/components/pages/testset/modals/index.tsx
  agenta-web/src/contexts/app.context.tsx
  agenta-web/src/contexts/project.context.tsx
  agenta-web/src/lib/helpers/evaluate.ts
  agenta-web/src/pages/testsets/[testset_id]/index.tsx
  agenta-web/src/pages/testsets/index.tsx
  agenta-web/src/services/app-selector/api/index.ts
  agenta-web/src/services/evaluations/api/index.ts
  agenta-web/src/services/testsets/api/index.ts
  cookbook/evaluations_with_sdk.ipynb
  docs/docs/evaluation/02-create-test-sets.mdx
  docs/docs/evaluation/05-sdk-evaluation.mdx
  docs/docs/reference/api/create-testset.api.mdx
  docs/docs/reference/api/fetch-evaluation-ids-evaluations-by-resource-get.api.mdx
  docs/docs/reference/openapi.json
  docs/docs/tutorials/sdk/evaluate-with-SDK.mdx
  response.txt
Labels: Frontend, Backend, size:L, lgtm

#2297 fix edge case llm-as-a-judge
  agenta-backend/agenta_backend/services/evaluators_service.py
Labels: bug, size:XS

#2298 Fix to the docs build
  docs/docs/reference/api/fetch-evaluation-ids-evaluations-by-resource-get.api.mdx
Labels: documentation, size:L

#2276 Build/AGE-1325-run-nextjs-outside-of-docker
  agenta-backend/agenta_backend/main.py
  agenta-web/.env.local
  agenta-web/next.config.js
  agenta-web/package.json
  docker-compose.yml
  restart_docker.sh
  run_oss.sh
  start_web_standalone.sh
Labels: nextjs, size:M, lgtm

#2291 (frontend)[AGE-1269]: (bug observability) Review Accordion height (not dynamic), margin, and padding
  agenta-web/src/components/pages/observability/components/AccordionTreePanel.tsx
Labels: bug, Frontend, size:M, lgtm

#2299 [Bug Fix]: Resolve CLI commands failing tests
  .github/actions/check-app-accessibility/action.yml
  .github/workflows/cli-commands-tests.yml
  agenta-backend/README.md
  agenta-cli/pyproject.toml
Labels: bug, CLI, size:M, lgtm

#2286 [Fix] verbosity in tracing
  agenta-cli/agenta/sdk/agenta_init.py
  agenta-cli/agenta/sdk/decorators/routing.py
  agenta-cli/agenta/sdk/litellm/litellm.py
  agenta-cli/agenta/sdk/middleware/auth.py
  agenta-cli/agenta/sdk/tracing/context.py
  agenta-cli/agenta/sdk/tracing/processors.py
  agenta-cli/agenta/sdk/tracing/tracing.py
  agenta-cli/agenta/sdk/utils/debug.py
  agenta-cli/agenta/sdk/utils/exceptions.py
  agenta-cli/agenta/sdk/utils/logging.py
Labels: SDK, size:L, lgtm

#2274 Add --force to generate cookbook
  cookbook/README.md
  docs/Makefile
  docs/scripts/generate_cookbooks.py
Labels: documentation, size:M, lgtm

#2277 [Feature] Observability: Inline traces
  agenta-backend/agenta_backend/services/evaluators_service.py
  agenta-backend/agenta_backend/services/llm_apps_service.py
  agenta-backend/agenta_backend/tests/unit/test_evaluators.py
  agenta-backend/agenta_backend/tests/unit/test_traces.py
  agenta-backend/agenta_backend/utils/traces.py
  agenta-cli/agenta/client/backend/__init__.py
  agenta-cli/agenta/client/backend/client.py
  agenta-cli/agenta/client/backend/core/http_client.py
  agenta-cli/agenta/client/backend/observability/client.py
  agenta-cli/agenta/client/backend/observability_v_1/__init__.py
  agenta-cli/agenta/client/backend/observability_v_1/client.py
  agenta-cli/agenta/client/backend/observability_v_1/types/__init__.py
  agenta-cli/agenta/client/backend/observability_v_1/types/format.py
  agenta-cli/agenta/client/backend/observability_v_1/types/query_traces_response.py
  agenta-cli/agenta/client/backend/types/__init__.py
  agenta-cli/agenta/client/backend/types/agenta_node_dto.py
  agenta-cli/agenta/client/backend/types/agenta_node_dto_nodes_value.py
  agenta-cli/agenta/client/backend/types/agenta_nodes_response.py
  agenta-cli/agenta/client/backend/types/agenta_root_dto.py
  agenta-cli/agenta/client/backend/types/agenta_roots_response.py
  agenta-cli/agenta/client/backend/types/agenta_tree_dto.py
  agenta-cli/agenta/client/backend/types/agenta_trees_response.py
  agenta-cli/agenta/client/backend/types/collect_status_response.py
  agenta-cli/agenta/client/backend/types/exception_dto.py
  agenta-cli/agenta/client/backend/types/link_dto.py
  agenta-cli/agenta/client/backend/types/node_dto.py
  agenta-cli/agenta/client/backend/types/node_type.py
  agenta-cli/agenta/client/backend/types/o_tel_context_dto.py
  agenta-cli/agenta/client/backend/types/o_tel_event_dto.py
  agenta-cli/agenta/client/backend/types/o_tel_extra_dto.py
  agenta-cli/agenta/client/backend/types/o_tel_link_dto.py
  agenta-cli/agenta/client/backend/types/o_tel_span_dto.py
  agenta-cli/agenta/client/backend/types/o_tel_span_kind.py
  agenta-cli/agenta/client/backend/types/o_tel_spans_response.py
  agenta-cli/agenta/client/backend/types/o_tel_status_code.py
  agenta-cli/agenta/client/backend/types/parent_dto.py
  agenta-cli/agenta/client/backend/types/root_dto.py
  agenta-cli/agenta/client/backend/types/span_dto.py
  agenta-cli/agenta/client/backend/types/span_dto_nodes_value.py
  agenta-cli/agenta/client/backend/types/status_code.py
  agenta-cli/agenta/client/backend/types/status_dto.py
  agenta-cli/agenta/client/backend/types/time_dto.py
  agenta-cli/agenta/client/backend/types/tree_dto.py
  agenta-cli/agenta/client/backend/types/tree_type.py
  agenta-cli/agenta/client/backend/variants/client.py
  agenta-cli/agenta/sdk/__init__.py
  agenta-cli/agenta/sdk/decorators/routing.py
  agenta-cli/agenta/sdk/tracing/inline.py
  agenta-cli/agenta/sdk/types.py
  agenta-web/src/components/Playground/Views/TestView.tsx
  agenta-web/src/components/pages/observability/ObservabilityDashboard.tsx
  agenta-web/src/components/pages/observability/drawer/TraceContent.tsx
  agenta-web/src/components/pages/observability/drawer/TraceHeader.tsx
  agenta-web/src/components/pages/observability/drawer/TraceTree.tsx
  agenta-web/src/lib/Types.ts
  agenta-web/src/lib/helpers/playgroundResp.ts
  agenta-web/src/lib/transformers.ts
  agenta-web/src/services/observability/types/index.ts
Labels: enhancement, Backend, CLI, tests, size:XXL

#2300 set prettier version
  .github/workflows/check-web-code-prettier.yml
Labels: ci/cd, size:XS

#2304 [Fix] clean up in-app auth docs and clean up in-app llm app URLs
  agenta-web/src/code_snippets/endpoints/fetch_config/curl.ts
  agenta-web/src/code_snippets/endpoints/fetch_config/python.ts
  agenta-web/src/code_snippets/endpoints/fetch_config/typescript.ts
  agenta-web/src/code_snippets/endpoints/invoke_llm_app/curl.ts
  agenta-web/src/code_snippets/endpoints/invoke_llm_app/python.ts
  agenta-web/src/code_snippets/endpoints/invoke_llm_app/typescript.ts
  agenta-web/src/components/pages/overview/deployments/DeploymentDrawer.tsx
  agenta-web/src/pages/apps/[app_id]/endpoints/index.tsx
  agenta-web/src/services/api.ts
Labels: typescript, size:M, lgtm

#2303 [Fix] Remove Auth Cache + Fix t`ree=None`
  agenta-cli/agenta/sdk/decorators/routing.py
  agenta-cli/agenta/sdk/middleware/auth.py
Labels: SDK, size:XS, lgtm

#2307 fix(frontend): wait until project-id gets loaded
  agenta-web/src/components/Layout/Layout.tsx
  agenta-web/src/contexts/project.context.tsx
Labels: Frontend, size:S

#2309 [Fix] CORS issue with old SDK
  agenta-web/src/services/api.ts
Labels: bug, size:L, lgtm

#2310 [Fix] missing `project_id` in auth middleware in SDK
  agenta-cli/agenta/sdk/middleware/auth.py
Labels: bug, SDK, size:XS, lgtm

#2311 [Fix] failed calls in Evaluations due to 401
  agenta-web/src/components/EvaluationTable/ABTestingEvaluationTable.tsx
  agenta-web/src/components/EvaluationTable/SingleModelEvaluationTable.tsx
Labels: bug, size:XS, lgtm

#2312 [Bug Fix]: Cannot run human evaluation for mflix app
  agenta-backend/agenta_backend/models/shared_models.py
Labels: bug, size:XS

#2315 sync versions
  agenta-backend/pyproject.toml
  agenta-web/package.json
Labels: dependencies, size:XS, lgtm

#2318 Remove deprecated icon attribution README.md
  README.md
Labels: documentation, size:XS

#2322 Update README.md in cli folder
  agenta-cli/README.md
Labels: documentation, CLI, size:L

#2321 (frontend)[AGE-1374]: Regression wrong time shown in traces
  agenta-web/src/components/Playground/Views/TestView.tsx
  agenta-web/src/components/pages/observability/ObservabilityDashboard.tsx
  agenta-web/src/components/pages/observability/drawer/TraceContent.tsx
  agenta-web/src/components/pages/observability/drawer/TraceTree.tsx
Labels: bug, Frontend, size:S, lgtm

#2314 NextJS turbo in dev mode
  agenta-web/package.json
Labels: nextjs, size:XS

#2324 Merge
  README.md
  agenta-backend/pyproject.toml
  agenta-cli/README.md
  agenta-cli/pyproject.toml
  agenta-web/package-lock.json
  agenta-web/package.json
  agenta-web/src/components/Playground/Views/TestView.tsx
  agenta-web/src/components/pages/observability/ObservabilityDashboard.tsx
  agenta-web/src/components/pages/observability/drawer/TraceContent.tsx
  agenta-web/src/components/pages/observability/drawer/TraceTree.tsx
Labels: size:L

#2320 Tutorial AI Code Reviewer
  docs/docs/tutorials/cookbooks/AI-powered-code-reviews.mdx
  docs/static/images/cookbooks/ai-powered-code-reviews/code-review-demo.gif
  docs/static/images/cookbooks/ai-powered-code-reviews/observability-pr.gif
  docs/static/images/cookbooks/ai-powered-code-reviews/pr-configure.png
  docs/static/images/cookbooks/ai-powered-code-reviews/pr-deploy.png
  docs/static/images/cookbooks/ai-powered-code-reviews/pr-human-eval.png
  docs/static/images/cookbooks/ai-powered-code-reviews/pr-playground.png
  docs/static/images/cookbooks/ai-powered-code-reviews/pr-prod.png
  docs/static/images/cookbooks/ai-powered-code-reviews/pr-run-eval.png
  examples/custom_workflows/ai-code-reviewer/.env.example
  examples/custom_workflows/ai-code-reviewer/ai-code-reviewer.py
  examples/custom_workflows/ai-code-reviewer/requirements.txt
Labels: documentation, example, size:L

#2327 merge
  .github/actions/check-app-accessibility/action.yml
  .github/workflows/cli-commands-tests.yml
  agenta-backend/README.md
  docs/docs/tutorials/cookbooks/AI-powered-code-reviews.mdx
  docs/static/images/cookbooks/ai-powered-code-reviews/code-review-demo.gif
  docs/static/images/cookbooks/ai-powered-code-reviews/observability-pr.gif
  docs/static/images/cookbooks/ai-powered-code-reviews/pr-configure.png
  docs/static/images/cookbooks/ai-powered-code-reviews/pr-deploy.png
  docs/static/images/cookbooks/ai-powered-code-reviews/pr-human-eval.png
  docs/static/images/cookbooks/ai-powered-code-reviews/pr-playground.png
  docs/static/images/cookbooks/ai-powered-code-reviews/pr-prod.png
  docs/static/images/cookbooks/ai-powered-code-reviews/pr-run-eval.png
  examples/custom_workflows/ai-code-reviewer/.env.example
  examples/custom_workflows/ai-code-reviewer/ai-code-reviewer.py
  examples/custom_workflows/ai-code-reviewer/requirements.txt
Labels: size:L
