Repository Agenta-AI/agenta, pull requests merged in 2025-05, with the labels that each got.

#2617 release/v0.44.3
  api/oss/src/apis/fastapi/observability/opentelemetry/otlp.py
  api/oss/src/services/analytics_service.py
  api/pyproject.toml
  sdk/poetry.lock
  sdk/pyproject.toml
  services/chat/requirements.txt
  services/completion/requirements.txt
  web/oss/package.json
  web/package.json
Labels: dependencies, size:L

#2619 release/v0.44.4
  api/oss/src/routers/evaluators_router.py
  api/oss/src/services/evaluators_service.py
  api/oss/src/services/llm_apps_service.py
  api/pyproject.toml
  sdk/pyproject.toml
  web/oss/package.json
  web/oss/src/components/EvaluationTable/SingleModelEvaluationTable.tsx
  web/oss/src/components/HumanEvaluationModal/HumanEvaluationModal.tsx
  web/oss/src/lib/hooks/useStatelessVariants/middlewares/appSchema/index.ts
  web/oss/src/lib/shared/variant/transformer.ts
  web/oss/src/lib/shared/variant/transformer/transformer.ts
  web/oss/src/lib/shared/variant/utils.ts
  web/package.json
Labels: size:L, lgtm

#2624 Fix: Correct default variable syntax in docker-compose.gh.yml
  hosting/docker-compose/oss/docker-compose.gh.yml
Labels: bug, size:XS, lgtm

#2627 Fix contributors
  .all-contributorsrc
  README.md
Labels: documentation, size:S
