Repository Agenta-AI/agenta, pull requests merged in 2025-01, with the labels that each got.

#2412 Release/v0.31.0
  agenta-backend/agenta_backend/models/api/evaluation_model.py
  agenta-backend/agenta_backend/routers/app_router.py
  agenta-backend/agenta_backend/routers/permissions_router.py
  agenta-backend/agenta_backend/services/helpers.py
  agenta-backend/pyproject.toml
  agenta-cli/agenta/__init__.py
  agenta-cli/agenta/client/backend/types/provider_kind.py
  agenta-cli/agenta/client/client.py
  agenta-cli/agenta/sdk/__init__.py
  agenta-cli/agenta/sdk/agenta_init.py
  agenta-cli/agenta/sdk/assets.py
  agenta-cli/agenta/sdk/context/exporting.py
  agenta-cli/agenta/sdk/context/routing.py
  agenta-cli/agenta/sdk/context/tracing.py
  agenta-cli/agenta/sdk/decorators/routing.py
  agenta-cli/agenta/sdk/decorators/tracing.py
  agenta-cli/agenta/sdk/managers/config.py
  agenta-cli/agenta/sdk/managers/secrets.py
  agenta-cli/agenta/sdk/middleware/auth.py
  agenta-cli/agenta/sdk/middleware/cache.py
  agenta-cli/agenta/sdk/middleware/config.py
  agenta-cli/agenta/sdk/middleware/cors.py
  agenta-cli/agenta/sdk/middleware/otel.py
  agenta-cli/agenta/sdk/middleware/vault.py
  agenta-cli/agenta/sdk/tracing/context.py
  agenta-cli/agenta/sdk/tracing/exporters.py
  agenta-cli/agenta/sdk/tracing/inline.py
  agenta-cli/agenta/sdk/tracing/processors.py
  agenta-cli/agenta/sdk/tracing/tracing.py
  agenta-cli/agenta/sdk/utils/constants.py
  agenta-cli/agenta/sdk/utils/exceptions.py
  agenta-cli/agenta/sdk/utils/globals.py
  agenta-cli/agenta/sdk/utils/timing.py
  agenta-cli/pyproject.toml
  agenta-cli/tests/baggage/_main.py
  agenta-cli/tests/baggage/agenta
  agenta-cli/tests/baggage/app.py
  agenta-cli/tests/baggage/config.toml
  agenta-cli/tests/baggage/specs/check_generate.py
  agenta-cli/tests/baggage/specs/check_openapi.py
  agenta-cli/tests/run_pytest.sh
  agenta-cli/tests/run_tests.sh
  agenta-cli/tests/start_server.sh
  agenta-cli/tests/stop_server.sh
  agenta-web/cypress/support/commands/evaluations.ts
  agenta-web/package-lock.json
  agenta-web/package.json
  agenta-web/src/components/pages/app-management/index.tsx
  agenta-web/src/components/pages/evaluations/NewEvaluation/NewEvaluationModal.tsx
  agenta-web/src/components/pages/settings/Secrets/Secrets.tsx
  agenta-web/src/hooks/useVaultSecret.ts
  agenta-web/src/lib/helpers/dynamic.ts
  agenta-web/src/lib/helpers/llmProviders.ts
  agenta-web/src/lib/helpers/utils.ts
Labels: Backend, CLI, SDK, size:XXL

#2411 [feature] shared services - create variants from service key
  agenta-backend/agenta_backend/migrations/postgres/versions/0f086ebc2f82_added_the_app_type_column_to_the_app_db_.py
  agenta-backend/agenta_backend/migrations/postgres/versions/0f086ebc2f83_extend_app_type.py
  agenta-backend/agenta_backend/models/api/api_models.py
  agenta-backend/agenta_backend/models/db_models.py
  agenta-backend/agenta_backend/models/shared_models.py
  agenta-backend/agenta_backend/routers/app_router.py
  agenta-backend/agenta_backend/services/app_manager.py
  agenta-backend/agenta_backend/services/db_manager.py
Labels: Backend, feature, size:L, lgtm

#2416 docs(app): added changelog soc2
  docs/blog/main.mdx
  docs/static/images/changelog/soc2_type1.png
Labels: documentation, size:M, lgtm

#2422 Update 01-how-to-integrate-with-agenta.mdx
  docs/docs/prompt-management/integration/01-how-to-integrate-with-agenta.mdx
Labels: documentation, size:XS, lgtm

#2417 [Feat]: New-playground Text Editor
  .husky/pre-push
  agenta-web/package-lock.json
  agenta-web/package.json
  agenta-web/src/components/Editor/Editor.tsx
  agenta-web/src/components/Editor/assets/theme.ts
  agenta-web/src/components/Editor/hooks/useEditorConfig/index.ts
  agenta-web/src/components/Editor/hooks/useEditorInvariant.ts
  agenta-web/src/components/Editor/hooks/useEditorResize.ts
  agenta-web/src/components/Editor/plugins/code/CodeActionMenuPlugin/PrettierButton/index.tsx
  agenta-web/src/components/Editor/plugins/code/CodeActionMenuPlugin/PrettierButton/prettierConfig.ts
  agenta-web/src/components/Editor/plugins/code/CodeActionMenuPlugin/index.tsx
  agenta-web/src/components/Editor/plugins/code/CodeEditorPlugin.tsx
  agenta-web/src/components/Editor/plugins/code/CodeFormatterPlugin/indentationRules.ts
  agenta-web/src/components/Editor/plugins/code/CodeFormatterPlugin/index.tsx
  agenta-web/src/components/Editor/plugins/code/CodeNode/CodeHighlightNode.ts
  agenta-web/src/components/Editor/plugins/code/CodeNode/CodeHighlighter/Plugin.tsx
  agenta-web/src/components/Editor/plugins/code/CodeNode/CodeHighlighter/index.ts
  agenta-web/src/components/Editor/plugins/code/CodeNode/CodeHighlighter/utils/codeNodeTransform.ts
  agenta-web/src/components/Editor/plugins/code/CodeNode/CodeHighlighter/utils/diff.ts
  agenta-web/src/components/Editor/plugins/code/CodeNode/CodeHighlighter/utils/gutter.ts
  agenta-web/src/components/Editor/plugins/code/CodeNode/CodeHighlighter/utils/handlers.ts
  agenta-web/src/components/Editor/plugins/code/CodeNode/CodeHighlighter/utils/helpers.ts
  agenta-web/src/components/Editor/plugins/code/CodeNode/CodeHighlighter/utils/invariant.ts
  agenta-web/src/components/Editor/plugins/code/CodeNode/CodeHighlighter/utils/selection.ts
  agenta-web/src/components/Editor/plugins/code/CodeNode/CodeHighlighter/utils/textTransform.ts
  agenta-web/src/components/Editor/plugins/code/CodeNode/CodeHighlighter/utils/tokenizer.ts
  agenta-web/src/components/Editor/plugins/code/CodeNode/CodeHighlighter/utils/types.d.ts
  agenta-web/src/components/Editor/plugins/code/CodeNode/CodeHighlighterPrism.tsx
  agenta-web/src/components/Editor/plugins/code/CodeNode/CodeLineNode.ts
  agenta-web/src/components/Editor/plugins/code/CodeNode/CodeNode.ts
  agenta-web/src/components/Editor/plugins/code/types.d.ts
  agenta-web/src/components/Editor/plugins/debug/DebugPlugin.tsx
  agenta-web/src/components/Editor/plugins/index.tsx
  agenta-web/src/components/Editor/plugins/singleline/SingleLinePlugin.tsx
  agenta-web/src/components/Editor/plugins/token/TokenInputNode.tsx
  agenta-web/src/components/Editor/plugins/token/TokenNode.ts
  agenta-web/src/components/Editor/plugins/token/TokenPlugin.tsx
  agenta-web/src/components/Editor/plugins/toolbar/ToolbarPlugin.tsx
  agenta-web/src/components/Editor/state/assets/atoms.ts
  agenta-web/src/components/Editor/state/index.tsx
  agenta-web/src/components/Editor/state/types.d.ts
  agenta-web/src/components/Editor/types.d.ts
Labels: Frontend, feature, typescript, size:XXL

#2402 Remove MongoDB
  agenta-backend/agenta_backend/apis/fastapi/observability/router.py
  agenta-backend/agenta_backend/dbs/postgres/shared/config.py
  agenta-backend/agenta_backend/dbs/postgres/shared/engine.py
  agenta-backend/agenta_backend/main.py
  agenta-backend/agenta_backend/migrations/mongo/backup.py
  agenta-backend/agenta_backend/migrations/mongo/v0_10_0_to_v0_11_0/20240131130415_updating_app_environment.py
  agenta-backend/agenta_backend/migrations/mongo/v0_10_0_to_v0_11_0/20240131132738_create_app_environment_revision.py
  agenta-backend/agenta_backend/migrations/mongo/v0_11_0_to_v0_12_0/20240126100524_models_revamp.py
  agenta-backend/agenta_backend/migrations/mongo/v0_11_0_to_v0_12_0/20240126144938_drop_organization_model.py
  agenta-backend/agenta_backend/migrations/mongo/v0_12_0_to_v0_16_0/20240509122536_evaluation_scenario_correct_answer.py
  agenta-backend/agenta_backend/migrations/mongo/v0_16_0_1_to_v0_16_0_2/20240603145957_code_evaluators.py
  agenta-backend/agenta_backend/migrations/mongo/v0_16_0_to_v0_16_0_1/20240602150517_evaluators.py
  agenta-backend/agenta_backend/migrations/mongo/v0_7_0_to_v0_8_0/20240110001454_initial_migration.py
  agenta-backend/agenta_backend/migrations/mongo/v0_7_0_to_v0_8_0/20240110132547_create_exact_match_evaluator_config.py
  agenta-backend/agenta_backend/migrations/mongo/v0_7_0_to_v0_8_0/20240110165900_evaluations_revamp.py
  agenta-backend/agenta_backend/migrations/mongo/v0_7_0_to_v0_8_0/20240112120721_evaluation_scenarios_revamp.py
  agenta-backend/agenta_backend/migrations/mongo/v0_7_0_to_v0_8_0/20240112120740_human_a_b_evaluation_scenarios.py
  agenta-backend/agenta_backend/migrations/mongo/v0_7_0_to_v0_8_0/20240112120800_human_single_model_evaluation_scenarios.py
  agenta-backend/agenta_backend/migrations/mongo/v0_7_0_to_v0_8_0/20240113131802_new_evaluation_results_aggregation.py
  agenta-backend/agenta_backend/migrations/mongo/v0_7_0_to_v0_8_0/20240113204909_change_odmantic_reference_to_link.py
  agenta-backend/agenta_backend/migrations/mongo/v0_8_0_to_v0_9_0/20240130133518_updating_app_variant.py
  agenta-backend/agenta_backend/migrations/mongo/v0_8_0_to_v0_9_0/20240130133544_create_app_variant_revision.py
  agenta-backend/agenta_backend/migrations/mongo/v0_8_0_to_v0_9_0/20240130133603_updating_app_environment.py
  agenta-backend/agenta_backend/migrations/mongo/v0_8_0_to_v0_9_0/20240130140202_connection_evaluation.py
  agenta-backend/agenta_backend/migrations/mongo/v0_9_0_to_v10_0_0/20240124174954_evaluation_error_handling.py
  agenta-backend/agenta_backend/migrations/mongo/v0_9_0_to_v10_0_0/20240124225808_evaluation_scenario_error_handling.py
  agenta-backend/agenta_backend/migrations/mongo_to_postgres/README.md
  agenta-backend/agenta_backend/migrations/mongo_to_postgres/db_engine.py
  agenta-backend/agenta_backend/migrations/mongo_to_postgres/docker-compose.migration.yml
  agenta-backend/agenta_backend/migrations/mongo_to_postgres/migration.py
  agenta-backend/agenta_backend/migrations/mongo_to_postgres/mongo_db_engine.py
  agenta-backend/agenta_backend/migrations/mongo_to_postgres/utils.py
  agenta-backend/agenta_backend/models/db/config.py
  agenta-backend/agenta_backend/models/db/postgres_engine.py
  agenta-backend/agenta_backend/routers/testset_router.py
  agenta-backend/agenta_backend/services/db_manager.py
  agenta-cli/agenta/client/backend/testsets/client.py
  docker-compose.gh.yml
  docker-compose.yml
Labels: Backend, size:XXL

#2423 [Feat]: Shared Service Tests
  agenta-backend/agenta_backend/pytest.ini
  agenta-backend/agenta_backend/routers/app_router.py
  agenta-backend/agenta_backend/services/variants_manager.py
  agenta-backend/agenta_backend/tests/configs_prompt/conftest.py
  agenta-backend/agenta_backend/tests/configs_prompt/test_configs_add.py
  agenta-backend/agenta_backend/tests/configs_prompt/test_configs_commit.py
  agenta-backend/agenta_backend/tests/configs_prompt/test_configs_delete.py
  agenta-backend/agenta_backend/tests/configs_prompt/test_configs_deploy.py
  agenta-backend/agenta_backend/tests/configs_prompt/test_configs_fetch.py
  agenta-backend/agenta_backend/tests/configs_prompt/test_configs_fork.py
  agenta-backend/agenta_backend/tests/configs_prompt/test_configs_history.py
  agenta-backend/agenta_backend/tests/configs_prompt/test_configs_list.py
  agenta-backend/agenta_backend/tests/variants_main_router/test_app_variant_router.py
  agenta-backend/poetry.lock
  agenta-backend/pyproject.toml
  agenta-cli/agenta/sdk/decorators/routing.py
  agenta-cli/agenta/sdk/decorators/tracing.py
  agenta-cli/agenta/sdk/litellm/litellm.py
  agenta-cli/agenta/sdk/litellm/mockllm.py
  agenta-cli/agenta/sdk/litellm/mocks/__init__.py
  agenta-cli/agenta/sdk/middleware/auth.py
  agenta-cli/agenta/sdk/middleware/config.py
  agenta-cli/agenta/sdk/tracing/exporters.py
  agenta-cli/agenta/sdk/tracing/inline.py
  agenta-cli/agenta/sdk/types.py
  services/completion/completion_service.py
Labels: Backend, feature, SDK, tests, size:XXL

#2426 [Feat]: New-playground Chat Generation UI
  agenta-web/package-lock.json
  agenta-web/package.json
  agenta-web/src/components/Editor/Editor.tsx
  agenta-web/src/components/Editor/assets/Editor.module.css
  agenta-web/src/components/Editor/hooks/useEditorConfig/index.ts
  agenta-web/src/components/Editor/plugins/index.tsx
  agenta-web/src/components/Editor/types.d.ts
  agenta-web/src/components/NewPlayground/Components/MainLayout/index.tsx
  agenta-web/src/components/NewPlayground/Components/Modals/LoadTestsetModal/assets/LoadTestsetButton/index.tsx
  agenta-web/src/components/NewPlayground/Components/PlaygroundGenerationComparisonView/GenerationComparisonChatInput/index.tsx
  agenta-web/src/components/NewPlayground/Components/PlaygroundGenerationComparisonView/GenerationComparisonChatInput/tpyes.d.ts
  agenta-web/src/components/NewPlayground/Components/PlaygroundGenerationComparisonView/GenerationComparisonChatOutput/index.tsx
  agenta-web/src/components/NewPlayground/Components/PlaygroundGenerationComparisonView/GenerationComparisonChatOutput/types.d.ts
  agenta-web/src/components/NewPlayground/Components/PlaygroundGenerationComparisonView/GenerationComparisonCompletionOutput/index.tsx
  agenta-web/src/components/NewPlayground/Components/PlaygroundGenerationComparisonView/GenerationComparisonHeader/index.tsx
  agenta-web/src/components/NewPlayground/Components/PlaygroundGenerationComparisonView/index.tsx
  agenta-web/src/components/NewPlayground/Components/PlaygroundGenerations/assets/GenerationChat/index.tsx
  agenta-web/src/components/NewPlayground/Components/PlaygroundGenerations/assets/GenerationChat/types.d.ts
  agenta-web/src/components/NewPlayground/Components/PlaygroundGenerations/assets/GenerationChatRow/index.tsx
  agenta-web/src/components/NewPlayground/Components/PlaygroundGenerations/assets/GenerationChatRow/types.d.ts
  agenta-web/src/components/NewPlayground/Components/PlaygroundGenerations/assets/GenerationCompletion/index.tsx
  agenta-web/src/components/NewPlayground/Components/PlaygroundGenerations/assets/GenerationCompletionRow/index.tsx
  agenta-web/src/components/NewPlayground/Components/PlaygroundGenerations/assets/GenerationHeader/index.tsx
  agenta-web/src/components/NewPlayground/Components/PlaygroundGenerations/assets/GenerationVariableOptions/index.tsx
  agenta-web/src/components/NewPlayground/Components/PlaygroundPromptComparisonView/PromptComparisonVariantNavigation/assets/VariantNavigationCard/index.tsx
  agenta-web/src/components/NewPlayground/Components/PlaygroundVariantConfigPrompt/assets/PlaygroundVariantConfigPromptCollapseContent.tsx
  agenta-web/src/components/NewPlayground/Components/PlaygroundVariantPropertyControl/assets/BooleanControl/index.tsx
  agenta-web/src/components/NewPlayground/Components/PlaygroundVariantPropertyControl/assets/MinMaxControl/index.tsx
  agenta-web/src/components/NewPlayground/Components/PlaygroundVariantPropertyControl/assets/MultiSelectControl/index.tsx
  agenta-web/src/components/NewPlayground/Components/PlaygroundVariantPropertyControl/assets/PromptMessageContent/assets/PromptMessageContentOptions.tsx
  agenta-web/src/components/NewPlayground/Components/PlaygroundVariantPropertyControl/assets/PromptMessageContent/index.tsx
  agenta-web/src/components/NewPlayground/Components/PlaygroundVariantPropertyControl/assets/PromptMessageContent/types.d.ts
  agenta-web/src/components/NewPlayground/Components/PlaygroundVariantPropertyControl/assets/PromptMessageUserSelect/index.tsx
  agenta-web/src/components/NewPlayground/Components/PlaygroundVariantPropertyControl/assets/SimpleDropdownSelect/index.tsx
  agenta-web/src/components/NewPlayground/Components/PlaygroundVariantPropertyControl/assets/TextControl/index.tsx
  agenta-web/src/components/NewPlayground/Components/PlaygroundVariantPropertyControl/assets/helpers.tsx
  agenta-web/src/components/NewPlayground/Components/PlaygroundVariantPropertyControl/index.tsx
  agenta-web/src/components/NewPlayground/Components/PlaygroundVariantPropertyControl/types.d.ts
  agenta-web/src/components/NewPlayground/Components/PromptMessageConfig/index.tsx
  agenta-web/src/components/NewPlayground/Components/PromptMessageConfig/types.d.ts
  agenta-web/src/components/NewPlayground/Components/types.d.ts
  agenta-web/src/components/NewPlayground/assets/utilities/hash.ts
  agenta-web/src/components/NewPlayground/assets/utilities/transformer/reverseTransformer.ts
  agenta-web/src/components/NewPlayground/assets/utilities/transformer/types/transformedVariant.d.ts
  agenta-web/src/components/NewPlayground/hooks/usePlayground/assets/comparisonHelpers.ts
  agenta-web/src/components/NewPlayground/hooks/usePlayground/assets/generationHelpers.ts
  agenta-web/src/components/NewPlayground/hooks/usePlayground/assets/helpers.ts
  agenta-web/src/components/NewPlayground/hooks/usePlayground/assets/inputHelpers.ts
  agenta-web/src/components/NewPlayground/hooks/usePlayground/assets/messageHelpers.ts
  agenta-web/src/components/NewPlayground/hooks/usePlayground/middlewares/appSchemaMiddleware.ts
  agenta-web/src/components/NewPlayground/hooks/usePlayground/middlewares/isVariantDirtyMiddleware.ts
  agenta-web/src/components/NewPlayground/hooks/usePlayground/middlewares/playgroundUIMiddleware.ts
  agenta-web/src/components/NewPlayground/hooks/usePlayground/middlewares/playgroundVariantMiddleware.ts
  agenta-web/src/components/NewPlayground/hooks/usePlayground/middlewares/playgroundVariantsMiddleware.ts
  agenta-web/src/components/NewPlayground/hooks/useWebWorker/assets/playground.worker.ts
  agenta-web/src/components/NewPlayground/state/index.tsx
  agenta-web/src/components/NewPlayground/state/types.d.ts
  agenta-web/tailwind.config.ts
  services/chat/chat_service.py
  services/test_deprecated/mock_agenta.py
Labels: Frontend, UI, reactjs, typescript, size:XL

#2399 [Fix] Prevent redirection from ProtectedRoute component if there's another route change is already happening
  agenta-web/src/components/ProtectedRoute/ProtectedRoute.tsx
Labels: bug, typescript, size:S, lgtm

#2397 (frontend)[Age 1401]: Collapsible side menu
  agenta-web/src/components/Layout/Layout.tsx
  agenta-web/src/components/Logo/Logo.tsx
  agenta-web/src/components/Sidebar/Sidebar.tsx
  agenta-web/src/components/Sidebar/config.tsx
Labels: Frontend, size:L

#2413 (frontend)[AGE-1486]: Illegal react operation due to changed order of rendered hooks
  agenta-web/src/components/Layout/Layout.tsx
  agenta-web/src/components/Sidebar/Sidebar.tsx
  agenta-web/src/components/Sidebar/config.tsx
  agenta-web/src/components/pages/app-management/index.tsx
  agenta-web/src/contexts/app.context.tsx
  agenta-web/src/contexts/org.context.tsx
  agenta-web/src/contexts/project.context.tsx
  agenta-web/src/lib/Types.ts
  agenta-web/src/lib/helpers/dynamic.ts
  agenta-web/src/services/app-selector/api/index.ts
  agenta-web/src/services/organization/api/index.ts
Labels: Frontend, size:L

#2401 (frontend)[Age 1397]: Display Confirmation modal when deleting one or multiple test sets in the test set view
  agenta-web/src/components/pages/testset/modals/DeleteTestset.tsx
  agenta-web/src/pages/testsets/index.tsx
Labels: Frontend, UX, size:L

#2398 [Feature]: Testing - Checkpoint 1 (Web)
  agenta-web-tests/.gitignore
  agenta-web-tests/README.md
  agenta-web-tests/package-lock.json
  agenta-web-tests/package.json
  agenta-web-tests/playwright.config.ts
  agenta-web-tests/playwright/config/deployments.ts
  agenta-web-tests/playwright/config/projects.ts
  agenta-web-tests/playwright/config/testTags.ts
  agenta-web-tests/playwright/config/types.d.ts
  agenta-web-tests/playwright/scripts/run-tests.ts
  agenta-web-tests/tests/cloud/app/README.md
  agenta-web-tests/tests/cloud/app/create.spec.ts
  agenta-web-tests/tests/cloud/app/helpers/test.ts
  agenta-web-tests/tests/cloud/app/types.ts
  agenta-web-tests/tests/fixtures/README.md
  agenta-web-tests/tests/fixtures/base.fixture/README.md
  agenta-web-tests/tests/fixtures/base.fixture/apiHelpers/README.md
  agenta-web-tests/tests/fixtures/base.fixture/apiHelpers/index.ts
  agenta-web-tests/tests/fixtures/base.fixture/apiHelpers/types.d.ts
  agenta-web-tests/tests/fixtures/base.fixture/index.ts
  agenta-web-tests/tests/fixtures/base.fixture/llmKeysSettingsHelpers/index.ts
  agenta-web-tests/tests/fixtures/base.fixture/types.ts
  agenta-web-tests/tests/fixtures/base.fixture/uiHelpers/README.md
  agenta-web-tests/tests/fixtures/base.fixture/uiHelpers/index.ts
  agenta-web-tests/tests/fixtures/base.fixture/uiHelpers/types.d.ts
  agenta-web-tests/tests/fixtures/session.fixture/index.ts
  agenta-web-tests/tests/fixtures/session.fixture/types.ts
  agenta-web-tests/tests/fixtures/types.d.ts
  agenta-web-tests/tests/fixtures/user.fixture/README.md
  agenta-web-tests/tests/fixtures/user.fixture/authHelpers/README.md
  agenta-web-tests/tests/fixtures/user.fixture/authHelpers/index.ts
  agenta-web-tests/tests/fixtures/user.fixture/authHelpers/types.d.ts
  agenta-web-tests/tests/fixtures/user.fixture/authHelpers/utilities.ts
  agenta-web-tests/tests/fixtures/user.fixture/index.ts
  agenta-web-tests/tests/fixtures/user.fixture/types.ts
  agenta-web-tests/tsconfig.json
  agenta-web-tests/utils/testmail/index.ts
  agenta-web-tests/utils/testmail/types.d.ts
Labels: feature, tests, size:XXL, lgtm

#2381 [Enhance]: eliminate-overwriting code
  agenta-web/.eslintrc.json
  agenta-web/next.config.js
  agenta-web/src/_app.tsx
  agenta-web/src/components/Scripts/GlobalScripts.tsx
  agenta-web/src/lib/helpers/analytics/AgPosthogProvider.tsx
  agenta-web/src/lib/helpers/analytics/assets/constants.ts
  agenta-web/src/lib/helpers/analytics/types.d.ts
  agenta-web/src/lib/helpers/auth/AuthProvider.tsx
  agenta-web/src/lib/helpers/auth/types.d.ts
  agenta-web/src/lib/helpers/dynamic.ts
  agenta-web/src/lib/helpers/sentry/hook/useSentryIntegrations.ts
  agenta-web/src/pages/_app.tsx
  agenta-web/src/services/observability/api/index.ts
Labels: dev experience, nextjs, size:L

#2428 Docs update: fix slack links / add pricing
  README.md
  agenta-cli/README.md
  docs/docusaurus.config.ts
Labels: documentation, size:S, lgtm

#2429 [Enhancement]: add migration to extend app type
  agenta-backend/agenta_backend/migrations/postgres/versions/0f086ebc2f82_added_the_app_type_column_to_the_app_db_.py
  agenta-backend/agenta_backend/migrations/postgres/versions/0f086ebc2f83_extend_app_type.py
  agenta-backend/agenta_backend/models/db_models.py
  agenta-backend/agenta_backend/models/shared_models.py
Labels: enhancement, size:M, lgtm

#2430 (frontend)[Issue 2418]: Evaluation results cannot be downloaded as CSV
  agenta-web/package-lock.json
  agenta-web/package.json
  agenta-web/src/lib/helpers/agGrid.tsx
Labels: Frontend, size:S

#2432 Changelog 32 / 30 / 29
  docs/blog/main.mdx
  docs/static/images/changelog/changelog_onboarding1.png
  docs/static/images/changelog/changelog_onboarding2.png
  docs/static/images/changelog/changelog_sidebar.gif
Labels: documentation, UI, size:L

#2437 fix(app): modified model config defaults to none
  agenta-cli/agenta/sdk/types.py
Labels: SDK, size:S

#2438 Fix/updated curly vars and chat prompt
  agenta-cli/agenta/sdk/types.py
  services/chat/chat_service.py
  services/completion/completion_service.py
Labels: size:XS

#2441 Fix[AGE-1392] Improve editor scroll behavior in AccordionTreePanel
  agenta-web/src/components/pages/observability/components/AccordionTreePanel.tsx
Labels: typescript, size:S, lgtm, ux bug

#2443 [Bug Fix]: Broken Observability in Shared Services
  agenta-backend/agenta_backend/services/llm_apps_service.py
  agenta-backend/agenta_backend/tasks/evaluations.py
  agenta-cli/agenta/sdk/middleware/auth.py
  agenta-cli/agenta/sdk/middleware/config.py
Labels: bug, size:S

#2444 Enhance[AGE-1430]: Improved comparison layout for new playground
  agenta-web/src/components/Editor/Editor.tsx
  agenta-web/src/components/Editor/plugins/index.tsx
  agenta-web/src/components/Editor/types.d.ts
  agenta-web/src/components/NewPlayground/Components/MainLayout/index.tsx
  agenta-web/src/components/NewPlayground/Components/Modals/CommitVariantChangesModal/index.tsx
  agenta-web/src/components/NewPlayground/Components/PlaygroundGenerationComparisonView/GenerationComparisonChatOutput/index.tsx
  agenta-web/src/components/NewPlayground/Components/PlaygroundGenerationComparisonView/GenerationComparisonChatOutput/types.d.ts
  agenta-web/src/components/NewPlayground/Components/PlaygroundGenerationComparisonView/GenerationComparisonCompletionOutput/index.tsx
  agenta-web/src/components/NewPlayground/Components/PlaygroundGenerationComparisonView/index.tsx
  agenta-web/src/components/NewPlayground/Components/PlaygroundGenerations/assets/GenerationChat/index.tsx
  agenta-web/src/components/NewPlayground/Components/PlaygroundGenerations/assets/GenerationChatRow/index.tsx
  agenta-web/src/components/NewPlayground/Components/PlaygroundGenerations/assets/GenerationChatRow/types.d.ts
  agenta-web/src/components/NewPlayground/Components/PlaygroundGenerations/assets/GenerationCompletion/index.tsx
  agenta-web/src/components/NewPlayground/Components/PlaygroundGenerations/assets/GenerationCompletionRow/index.tsx
  agenta-web/src/components/NewPlayground/Components/PlaygroundGenerations/assets/GenerationVariableOptions/index.tsx
  agenta-web/src/components/NewPlayground/Components/PlaygroundGenerations/index.tsx
  agenta-web/src/components/NewPlayground/Components/PlaygroundVariantConfigPrompt/assets/PlaygroundVariantConfigPromptCollapseContent.tsx
  agenta-web/src/components/NewPlayground/Components/PlaygroundVariantConfigPrompt/index.tsx
  agenta-web/src/components/NewPlayground/Components/PlaygroundVariantPropertyControl/assets/PromptMessageContent/assets/PromptMessageContentOptions.tsx
  agenta-web/src/components/NewPlayground/Components/PlaygroundVariantPropertyControl/assets/PromptMessageContent/assets/types.d.ts
  agenta-web/src/components/NewPlayground/Components/PlaygroundVariantPropertyControl/assets/TextControl/index.tsx
  agenta-web/src/components/NewPlayground/Components/PromptMessageConfig/index.tsx
  agenta-web/src/components/NewPlayground/Components/PromptMessageConfig/types.d.ts
  agenta-web/src/components/NewPlayground/Components/SharedEditor/index.tsx
  agenta-web/src/components/NewPlayground/Components/SharedEditor/types.d.ts
  agenta-web/src/components/NewPlayground/assets/AddButton.tsx
  agenta-web/src/components/NewPlayground/hooks/usePlayground/assets/generationHelpers.ts
  agenta-web/src/components/NewPlayground/hooks/usePlayground/assets/helpers.ts
  agenta-web/src/components/NewPlayground/hooks/usePlayground/middlewares/isVariantDirtyMiddleware.ts
  agenta-web/src/components/NewPlayground/hooks/usePlayground/middlewares/playgroundVariantMiddleware.ts
  agenta-web/src/components/NewPlayground/hooks/usePlayground/middlewares/playgroundVariantsMiddleware.ts
  agenta-web/src/components/Playground/index.tsx
  agenta-web/src/components/pages/evaluations/autoEvaluation/AutoEvaluation.tsx
  agenta-web/src/components/pages/overview/deployments/DeploymentDrawer/index.tsx
  agenta-web/src/lib/hooks/useStatelessVariant/middlewares/appSchemaMiddleware.ts
  agenta-web/src/pages/apps/[app_id]/endpoints/index.tsx
  agenta-web/src/services/api.ts
  agenta-web/src/styles/globals.css
Labels: Frontend, size:XXL
