Repository Agenta-AI/agenta, pull requests merged in 2025-02, with the labels that each got.

#2445 refactor(sdk): improve errors in middleware auth
  agenta-cli/agenta/sdk/middleware/auth.py
Labels: SDK, refactoring, size:L

#2442 (docs) Fix the issue with gh docker file working with ports different than 80
  README.md
  agenta-backend/agenta_backend/services/app_manager.py
  agenta-cli/README.md
  agenta-web/prod.gh.Dockerfile
  docker-compose.gh.yml
  docs/docs/misc/contributing/development-mode.mdx
  docs/docs/self-host/deploy_remotly/01-host-remotely.mdx
  docs/docs/self-host/deploy_remotly/02-host-on-aws.mdx
  docs/docs/self-host/deploy_remotly/03-host-on-gcp.mdx
  docs/docs/self-host/deploy_remotly/04-host-on-kubernetes.mdx
  docs/docs/self-host/deploy_remotly/host-remotely.mdx
  docs/docs/self-host/host-locally.mdx
Labels: bug, documentation, size:L

#2452 [Fix] Fix how large data is handled in new playground comparison ui
  agenta-web/src/components/EvaluationTable/ABTestingEvaluationTable.tsx
  agenta-web/src/components/NewPlayground/Components/Drawers/TestsetDrawer/index.tsx
  agenta-web/src/components/NewPlayground/Components/Drawers/TraceDrawer/index.tsx
  agenta-web/src/components/NewPlayground/Components/Modals/CommitVariantChangesModal/index.tsx
  agenta-web/src/components/NewPlayground/Components/Modals/DeleteVariantModal/index.tsx
  agenta-web/src/components/NewPlayground/Components/PlaygroundGenerationComparisonView/GenerationComparisonChatOutput/index.tsx
  agenta-web/src/components/NewPlayground/Components/PlaygroundGenerationComparisonView/GenerationComparisonCompletionOutput/index.tsx
  agenta-web/src/components/NewPlayground/Components/PlaygroundGenerations/assets/GenerationChat/index.tsx
  agenta-web/src/components/NewPlayground/Components/PlaygroundGenerations/assets/GenerationChatRow/index.tsx
  agenta-web/src/components/NewPlayground/Components/PlaygroundGenerations/assets/GenerationCompletion/index.tsx
  agenta-web/src/components/NewPlayground/Components/PlaygroundGenerations/assets/GenerationCompletionRow/index.tsx
  agenta-web/src/components/NewPlayground/Components/PlaygroundGenerations/assets/GenerationHeader/index.tsx
  agenta-web/src/components/NewPlayground/Components/PlaygroundGenerations/assets/GenerationVariableOptions/index.tsx
  agenta-web/src/components/NewPlayground/Components/PlaygroundPromptComparisonView/PromptComparisonVariantNavigation/assets/VariantNavigationCard/index.tsx
  agenta-web/src/components/NewPlayground/Components/PlaygroundVariantModelConfig/index.tsx
  agenta-web/src/components/NewPlayground/assets/hash.ts
  agenta-web/src/components/NewPlayground/hooks/usePlayground/assets/helpers.ts
  agenta-web/src/components/NewPlayground/hooks/usePlayground/middlewares/isVariantDirtyMiddleware.ts
  agenta-web/src/components/NewPlayground/hooks/usePlayground/middlewares/playgroundVariantMiddleware.ts
  agenta-web/src/components/NewPlayground/hooks/usePlayground/middlewares/playgroundVariantsMiddleware.ts
  agenta-web/src/components/NewPlayground/hooks/usePlayground/types.d.ts
  agenta-web/src/components/NewPlayground/hooks/useWebWorker/index.ts
  agenta-web/src/components/NewPlayground/state/index.tsx
  agenta-web/src/components/NewPlayground/v2/components/Drawers/GenerationFocusDrawer/index.tsx
  agenta-web/src/components/Playground/index.tsx
  agenta-web/src/components/pages/overview/deployments/DeploymentDrawer/index.tsx
  agenta-web/src/lib/api/SWRConfig.tsx
  agenta-web/src/lib/api/types.ts
  agenta-web/src/lib/hooks/useStatelessVariant/types.d.ts
Labels: bug, size:XL

#2453 Frontend [AGE-1340]: Fix cache related issue that is breaking human a/b eval
  agenta-web/src/components/NewPlayground/hooks/usePlayground/assets/helpers.ts
  agenta-web/src/lib/hooks/useStatelessVariant/middlewares/appSchemaMiddleware.ts
  agenta-web/src/services/api.ts
Labels: Frontend, size:S

#2448 Changelog v33
  docs/blog/main.mdx
Labels: documentation, size:S, lgtm

#2454 docs(app): updated playground page
  docs/docs/getting-started/01-introduction.mdx
  docs/docs/prompt-management/01-overview.mdx
  docs/docs/prompt-management/04-using-the-playground.mdx
Labels: documentation, size:L, lgtm

#2455 Minor fix docs changelog
  docs/blog/main.mdx
Labels: documentation, size:XS

#2461 [Fix] hide settings temporarily
  agenta-web/src/components/Sidebar/hooks/useSidebarConfig/index.tsx
Labels: size:XS

#2460 [Fix] single bracket variable detection in the new playground
  agenta-web/src/components/NewPlayground/hooks/usePlayground/assets/inputHelpers.ts
Labels: bug, documentation, size:XS

#2458 feat(sdk): update model list
  agenta-cli/agenta/sdk/assets.py
Labels: feature, SDK, size:L

#2466 [AGE 1517] Frontend: Fix apps fetching in playground root
  agenta-web/src/components/Playground/index.tsx
  agenta-web/src/contexts/app.context.tsx
Labels: Frontend, size:XS

#2467 Revert "[AGE 1517] Frontend: Fix apps fetching in playground root"
  agenta-web/src/components/Playground/index.tsx
  agenta-web/src/contexts/app.context.tsx
Labels: Frontend, size:XS

#2468 [AGE 1517] Frontend: Fix apps fetching in playground root
  agenta-web/src/components/Playground/index.tsx
  agenta-web/src/contexts/app.context.tsx
Labels: bug, Frontend, size:XS

#2469 [Fix] `.gh` as single file
  agenta-cli/agenta/sdk/middleware/auth.py
  docker-compose.gh.yml
  services/chat/docker-compose.gh.yml
  services/completion/docker-compose.gh.yml
Labels: SDK, size:L, lgtm

#2470 [Chore] Add LLM provider keys to `.env` in readme and docs
  agenta-cli/README.md
  docs/docs/self-host/host-locally.mdx
Labels: documentation, size:S, lgtm

#2476 fix(sdk): fixed issue with ag_config in config.py
  agenta-backend/pyproject.toml
  agenta-cli/agenta/sdk/managers/config.py
  agenta-cli/pyproject.toml
  agenta-web/package-lock.json
  agenta-web/package.json
Labels: SDK, size:S

#2478 [Chore] unify shared services docker compose
  docker-compose.yml
  services/chat/docker-compose.yml
  services/completion/docker-compose.yml
Labels: size:L, lgtm

#2473 (docs) fix to self-hosting documentation
  docs/docs/self-host/host-locally.mdx
Labels: documentation, size:XS

#1739 Renames agenta app Dockerfiles to non-trivial names
  agenta-backend/agenta_backend/services/container_manager.py
  agenta-cli/agenta/docker/docker-assets/Dockerfile.oss.template
  agenta-cli/agenta/docker/docker_utils.py
Labels: Backend, CLI, size:S, lgtm

#2481 docs: fix typo markdown in docs
  docs/docs/self-host/host-locally.mdx
Labels: documentation, size:XS

#2482 [Hot fix]: Added project id to app creation api request
  agenta-web/src/components/Playground/index.tsx
  agenta-web/src/contexts/app.context.tsx
  agenta-web/src/services/app-selector/api/index.ts
Labels: Frontend, size:S

#2487 Dev new - clean history
  agenta-backend/pyproject.toml
  agenta-cli/agenta/docker/docker-assets/Dockerfile.template
  agenta-cli/pyproject.toml
  agenta-web/package-lock.json
  agenta-web/package.json
  agenta-web/src/components/Playground/index.tsx
  agenta-web/src/contexts/app.context.tsx
  agenta-web/src/services/app-selector/api/index.ts
  docs/docs/self-host/host-locally.mdx
  services/chat/docker-compose.yml
  services/completion/docker-compose.yml
Labels: documentation, size:L

#2489 [Hot Fix]: Replace crypto.randomUUID with uuidv4 for ID generation
  agenta-web/src/components/Editor/Editor.tsx
  agenta-web/src/components/NewPlayground/assets/utilities/genericTransformer/utilities/string.ts
  agenta-web/src/lib/hooks/useStatelessVariant/assets/genericTransformer/utilities/string.ts
Labels: typescript, size:S

#2495 Hot Fix: Enhance evaluator configuration button to reset current state on open
  agenta-web/src/components/pages/evaluations/autoEvaluation/AutoEvaluation.tsx
  agenta-web/src/components/pages/evaluations/autoEvaluation/EvaluatorsModal/EvaluatorsModal.tsx
  agenta-web/src/lib/helpers/utils.ts
  agenta-web/src/services/api.ts
Labels: UI, size:M

#2500 Hot Fix: Enhance evaluator configuration button to reset current state on open
  agenta-web/src/components/pages/evaluations/autoEvaluation/AutoEvaluation.tsx
  agenta-web/src/components/pages/evaluations/autoEvaluation/EvaluatorsModal/EvaluatorsModal.tsx
  agenta-web/src/lib/helpers/utils.ts
  agenta-web/src/services/api.ts
Labels: size:M

#2501 [AGE-1540](frontend): Latest variant version is not shown in the Configure evaluator
  agenta-web/src/lib/hooks/useStatelessVariant/middlewares/appSchemaMiddleware.ts
Labels: bug, Frontend, size:S

#2498 Fix JSON field match
  agenta-backend/agenta_backend/services/evaluators_service.py
Labels: bug, Backend, size:S

#2503 [Hot Fix]: Fix variantId bug in Configure Eval modal
  agenta-web/src/components/pages/evaluations/autoEvaluation/AutoEvaluation.tsx
  agenta-web/src/components/pages/evaluations/autoEvaluation/EvaluatorsModal/EvaluatorsModal.tsx
  agenta-web/src/lib/helpers/utils.ts
  agenta-web/src/services/api.ts
Labels: bug, Frontend, size:M

#2504 Release/v0.33.7
  agenta-web/src/components/pages/evaluations/autoEvaluation/AutoEvaluation.tsx
  agenta-web/src/components/pages/evaluations/autoEvaluation/EvaluatorsModal/EvaluatorsModal.tsx
  agenta-web/src/lib/helpers/utils.ts
  agenta-web/src/services/api.ts
Labels: typescript, size:M

#2509 release/v0.34.2
  hosting/docker-compose/oss/docker-compose.gh.yml
Labels: size:XS, lgtm

#2510 release/v0.34.2
  .gitignore
  examples/Readme.md
  hosting/docker-compose/run.sh
  web/package.json
Labels: size:S, lgtm

#2511 release/v0.34.3
  README.md
  api/pyproject.toml
  docs/blog/main.mdx
  docs/docs/misc/contributing/development-mode.mdx
  docs/docs/prompt-management/04-using-the-playground.mdx
  docs/docs/reference/sdk/04-deprecated-v2/_category_.json
  docs/docs/reference/sdk/04-deprecated-v2/core_functions/_category_.json
  docs/docs/reference/sdk/04-deprecated-v2/core_functions/config_datatypes.mdx
  docs/docs/reference/sdk/04-deprecated-v2/core_functions/config_default.mdx
  docs/docs/reference/sdk/04-deprecated-v2/core_functions/config_object.mdx
  docs/docs/reference/sdk/04-deprecated-v2/core_functions/config_pull.mdx
  docs/docs/reference/sdk/04-deprecated-v2/core_functions/config_push.mdx
  docs/docs/reference/sdk/04-deprecated-v2/core_functions/init.mdx
  docs/docs/reference/sdk/04-deprecated-v2/quick_start.mdx
  docs/docs/self-host/01-host-locally.mdx
  docs/docs/self-host/02-host-remotely.mdx
  docs/docs/self-host/03-host-on-kubernetes.mdx
  docs/docs/self-host/04-applying-schema-migration.mdx
  docs/docs/self-host/deploy_remotly/01-host-remotely.mdx
  docs/docs/self-host/deploy_remotly/02-host-on-aws.mdx
  docs/docs/self-host/deploy_remotly/03-host-on-gcp.mdx
  docs/docs/self-host/deploy_remotly/_category_.json
  docs/docs/self-host/host-locally.mdx
  docs/docs/self-host/migration/_category_.json
  docs/docs/self-host/migration/applying-schema-migration.mdx
  docs/docs/self-host/migration/migration-to-mongodb.mdx
  docs/docs/self-host/migration/migration-to-postgres.mdx
  docs/docusaurus.config.ts
  docs/static/images/simple-img.png
  docs/static/images/social-card.png
  sdk/README.md
  sdk/agenta/sdk/assets.py
  sdk/pyproject.toml
  web/oss/package.json
  web/package.json
Labels: documentation, size:XXL
