Repository Agenta-AI/agenta, pull requests merged in 2025-04, with the labels that each got.

#2565 release/v0.38.1
  api/pyproject.toml
  sdk/pyproject.toml
  web/oss/package.json
  web/oss/src/components/NewPlayground/hooks/usePlayground/middlewares/appSchemaMiddleware.ts
  web/oss/src/lib/hooks/useStatelessVariants/middlewares/appSchema/index.ts
  web/package.json
Labels: dependencies, size:S

#2567 release/v0.38.2
  api/pyproject.toml
  sdk/pyproject.toml
  web/oss/package.json
  web/oss/src/components/Layout/Layout.tsx
  web/oss/src/components/NewPlayground/Components/Menus/SelectVariant/assets/TreeSelectItemRenderer/index.tsx
  web/oss/src/components/NewPlayground/Components/Menus/SelectVariant/index.tsx
  web/oss/src/components/NewPlayground/Components/Modals/CreateVariantModal/assets/NewVariantButton/index.tsx
  web/oss/src/components/NewPlayground/hooks/usePlayground/middlewares/appSchemaMiddleware.ts
  web/oss/src/components/Sidebar/hooks/useSidebarConfig/index.tsx
  web/oss/src/components/pages/app-management/modals/CustomWorkflowModal/hooks/useCustomWorkflowConfig.tsx
  web/oss/src/components/pages/overview/variants/DeployVariantModal.tsx
  web/oss/src/lib/hooks/useStatelessVariants/middlewares/appSchema/index.ts
  web/oss/src/lib/hooks/useVariants.ts
  web/oss/src/lib/shared/variant/inputHelpers.ts
  web/oss/src/lib/shared/variant/transformer.ts
  web/oss/src/lib/shared/variant/transformer/transformer.ts
  web/oss/src/lib/shared/variant/transformer/types/transformedVariant.d.ts
  web/oss/src/lib/shared/variant/utils.ts
  web/oss/src/pages/apps/[app_id]/overview/index.tsx
  web/oss/src/services/deployment/hooks/useEnvironments/index.tsx
  web/package.json
Labels: dependencies, typescript, size:XL

#2569 release/v0.39.1
  api/pyproject.toml
  docs/docs/evaluation/02-create-test-sets.mdx
  docs/docs/tutorials/videos/creating-test-sets-from-production-data.md
  docs/sidebars.ts
  sdk/pyproject.toml
  web/oss/package.json
  web/package.json
Labels: documentation, dependencies, size:L, lgtm

#2573 release/v0.39.3
  api/oss/databases/postgres/migrations/data_migrations/projects.py
  api/oss/src/models/deprecated_models.py
  api/pyproject.toml
  sdk/pyproject.toml
  web/oss/package.json
  web/oss/src/components/Banners/BillingPlanBanner/FreePlanBanner.tsx
  web/oss/src/components/Banners/BillingPlanBanner/FreeTrialBanner.tsx
  web/oss/src/components/Sidebar/Sidebar.tsx
  web/oss/src/components/pages/settings/WorkspaceManage/Modals/InviteUsersModal.tsx
  web/oss/src/components/pages/settings/WorkspaceManage/WorkspaceManage.tsx
  web/oss/src/lib/noop/index.tsx
  web/oss/src/services/billing/index.tsx
  web/oss/src/services/billing/types.d.ts
  web/package.json
Labels: size:XL, lgtm

#2574 Update README.md
  README.md
Labels: documentation, size:L

#2580 release/v0.39.4
  README.md
  api/pyproject.toml
  sdk/README.md
  sdk/pyproject.toml
  web/oss/package.json
  web/oss/src/lib/shared/variant/transformer/transformer.ts
  web/package.json
Labels: size:L, lgtm

#2582 release/v0.40.0
  api/entrypoint.py
  api/oss/src/core/secrets/utils.py
  api/oss/src/models/api/evaluation_model.py
  api/oss/src/models/api/workspace_models.py
  api/oss/src/routers/variants_router.py
  api/oss/src/services/analytics_service.py
  api/oss/src/services/db_manager.py
  api/oss/src/services/helpers.py
  api/oss/src/services/llm_apps_service.py
  api/oss/src/services/organization_service.py
  api/poetry.lock
  api/pyproject.toml
  sdk/agenta/sdk/decorators/tracing.py
  sdk/agenta/sdk/tracing/attributes.py
  sdk/pyproject.toml
  web/oss/package.json
  web/oss/src/components/Layout/Layout.tsx
  web/oss/src/components/ModelRegistry/Drawers/ConfigureProviderDrawer/assets/ConfigureProviderDrawerContent.tsx
  web/oss/src/components/ModelRegistry/Modals/ConfigureProviderModal/assets/ConfigureProviderModalContent.tsx
  web/oss/src/components/ModelRegistry/Modals/ConfigureProviderModal/assets/types.d.ts
  web/oss/src/components/ModelRegistry/Modals/ConfigureProviderModal/index.tsx
  web/oss/src/components/ModelRegistry/Modals/DeleteProviderModal/assets/DeleteProviderModalContent.tsx
  web/oss/src/components/ProtectedRoute/ProtectedRoute.tsx
  web/oss/src/components/pages/auth/SendOTP/index.tsx
  web/oss/src/components/pages/auth/assets/types.d.ts
  web/oss/src/components/pages/evaluations/NewEvaluation/NewEvaluationModal.tsx
  web/oss/src/components/pages/evaluations/NewEvaluation/SelectVariantSection.tsx
  web/oss/src/components/pages/settings/Secrets/ModelRegistryTable/index.tsx
  web/oss/src/components/pages/settings/Secrets/SecretProviderTable/index.tsx
  web/oss/src/components/pages/settings/Secrets/Secrets.tsx
  web/oss/src/components/pages/settings/WorkspaceManage/Modals/InviteUsersModal.tsx
  web/oss/src/hooks/useVaultSecret.ts
  web/oss/src/lib/helpers/analytics/hooks/useSurvey.ts
  web/oss/src/lib/helpers/llmProviders.ts
  web/oss/src/pages/auth/[[...path]].tsx
  web/oss/src/pages/auth/callback/[[...callback]].tsx
  web/oss/src/pages/workspaces/accept.tsx
  web/oss/src/services/workspace/api/index.ts
  web/package.json
Labels: Frontend, Backend, size:XXL, lgtm

#2597 release/v0.41.1
  api/oss/databases/postgres/migrations/find_head.py
  api/oss/src/routers/testset_router.py
  api/oss/src/services/evaluators_service.py
  api/oss/src/services/llm_apps_service.py
  api/oss/tests/manual/testsets/create_testset_limits.py
  api/oss/tests/manual/testsets/test_testset_limits.py
  api/pyproject.toml
  docs/docs/getting-started/02-quick-start.mdx
  docs/docs/prompt-management/05-adding-custom-providers.mdx
  sdk/agenta/sdk/types.py
  sdk/pyproject.toml
  services/chat/oss/src/service.py
  services/completion/oss/src/service.py
  web/oss/cypress/e2e/1-smoke-tests.cy.ts
  web/oss/cypress/e2e/app-navigation.cy.ts
  web/oss/package.json
  web/oss/src/components/ModelRegistry/Modals/ConfigureProviderModal/index.tsx
  web/oss/src/components/ModelRegistry/Modals/DeleteProviderModal/index.tsx
  web/oss/src/components/NewPlayground/Components/PlaygroundVariantPropertyControl/assets/PromptMessageContent/assets/PromptMessageContentOptions.tsx
  web/oss/src/components/NewPlayground/hooks/usePlayground/middlewares/appSchemaMiddleware.ts
  web/oss/src/components/OldPlayground/Views/TestView.tsx
  web/oss/src/components/VariantsComponents/Drawers/VariantDrawer/assets/DeploymentDrawerTitle/index.tsx
  web/oss/src/components/VariantsComponents/Drawers/VariantDrawer/assets/Parameters/index.tsx
  web/oss/src/components/VariantsComponents/Drawers/VariantDrawer/assets/VariantDrawerContent/index.tsx
  web/oss/src/components/VariantsComponents/Drawers/VariantDrawer/assets/VariantDrawerTitle/index.tsx
  web/oss/src/components/VariantsComponents/Drawers/VariantDrawer/assets/types.d.ts
  web/oss/src/components/VariantsComponents/Drawers/VariantDrawer/index.tsx
  web/oss/src/components/VariantsComponents/Drawers/VariantDrawer/utils/index.ts
  web/oss/src/components/pages/app-management/index.tsx
  web/oss/src/components/pages/app-management/modals/AddAppFromTemplateModal/types.d.ts
  web/oss/src/components/pages/testset/modals/UploadTestset.tsx
  web/oss/src/lib/shared/variant/inputHelpers.ts
  web/oss/src/lib/shared/variant/transformer.ts
  web/oss/src/lib/shared/variant/transformer/transformToRequestBody.ts
  web/oss/src/lib/shared/variant/transformer/transformer.ts
  web/oss/src/lib/shared/variant/utils.ts
  web/oss/src/pages/settings/index.tsx
  web/oss/src/services/app-selector/api/index.ts
  web/package.json
Labels: documentation, python, typescript, size:XL

#2605 Hotfix self-hosting build by disabling typing
  web/oss/next.config.ts
Labels: bug, nextjs, size:XS

#2607 release/v0.42.1
  api/pyproject.toml
  sdk/pyproject.toml
  web/oss/next.config.ts
  web/oss/package.json
  web/oss/src/components/NewPlayground/hooks/usePlayground/middlewares/playgroundVariantMiddleware.ts
  web/package.json
Labels: dependencies, size:S
